/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/smallmap/earth2.gltf -o src/component/category/earth2.jsx -r “public” 
Author: T-FLEX CAD ST (Free) (https://sketchfab.com/tflexcad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/globe-earth-for-3d-printing-97500fadf3ff4b0db169fee3dbc65779
Title: Globe (Earth) - for 3D printing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Earth(props) {
  const { nodes, materials } = useGLTF(import.meta.env.VITE_S3_URL + 'Objects/Globe2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.001]} rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.AppBB} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.AppAB} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.AppAB} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
