/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: sheba1998 (https://sketchfab.com/sheba1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gbus-bus-stop-ba4808305d8544eca08c0dcffda79ef4
Title: Gbus Bus Stop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BusStop(props) {
  const { nodes, materials } = useGLTF(import.meta.env.VITE_S3_URL + 'Map/BusStop/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.FencePole} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.binpole1} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.binpole1} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.binpole1} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.binpole1} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.grass1} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.binlid} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.lambert6SG} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.lambert7SG} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.lambert7SG} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.lambert7SG} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.lambert8SG} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.lambert8SG} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.lambert9SG} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.lambert10SG} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.lambert11SG} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.lambert12SG} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.lambert13SG} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.lambert14SG} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.machine1} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.lambert15SG} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.lambert15SG} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.lambert15SG} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.lambert15SG} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.lambert16SG} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.lambert16SG} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.lambert17SGcamera} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.camerahold} />
          <mesh geometry={nodes.defaultMaterial_31.geometry} material={materials.grass1} />
          <mesh geometry={nodes.defaultMaterial_32.geometry} material={materials.FencePole} />
          <mesh geometry={nodes.defaultMaterial_33.geometry} material={materials.FencePole} />
          <mesh geometry={nodes.defaultMaterial_34.geometry} material={materials.Fence1} />
          <mesh geometry={nodes.defaultMaterial_35.geometry} material={materials.Fence1} />
          <mesh geometry={nodes.defaultMaterial_36.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_37.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_38.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_39.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.defaultMaterial_40.geometry} material={materials.lambert4SG} />
          <mesh geometry={nodes.defaultMaterial_41.geometry} material={materials.lambert4SG} />
          <mesh geometry={nodes.defaultMaterial_42.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.defaultMaterial_43.geometry} material={materials.lambert3SG} />
        </group>
      </group>
    </group>
  )
}