/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Merow (https://sketchfab.com/TehMerow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-convenience-store-d81380e64c2c4b85b4cf58910f649312
Title: The Convenience Store
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ConvenienceStore(props) {
  const { nodes, materials } = useGLTF(import.meta.env.VITE_S3_URL + 'Map/ConvenienceStore/scene.gltf')
  return (
    <group {...props} dispose={null} scale={2}>
      <group position={[4.856, 1.07, 0.873]} rotation={[0, 1.429, 0]} scale={0.171}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.register} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.register} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['register.screen']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.register} position={[-1.219, 0.902, -0.646]} scale={[1.668, 1.216, 1]} />
      </group>
      <group position={[5.687, 0, 3.515]} scale={1.146}>
        <mesh geometry={nodes.Object_26.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.merch} position={[0, 0.674, -0.145]} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.merch} position={[0, 0.777, -0.145]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.outline} position={[0, 0.674, -0.145]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.outline} position={[0, 0.777, -0.145]} />
      </group>
      <group position={[3.984, 0, 3.771]} scale={1.146}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.merch} position={[0, 0.674, -0.145]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.outline} position={[0, 0.674, -0.145]} />
      </group>
      <group position={[3.293, 0, 3.771]} scale={1.146}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.merch} position={[0, 0.674, -0.145]} />
      </group>
      <group position={[-1.482, 0, 1.717]} scale={0.58}>
        <mesh geometry={nodes.Object_47.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.shelf} position={[0, 1.057, -0.664]} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-3.507, 0, 1.717]} scale={0.58}>
        <mesh geometry={nodes.Object_56.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.shelf} position={[0, 1.057, -0.664]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[0.545, 0, 1.717]} scale={0.58}>
        <mesh geometry={nodes.Object_65.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.shelf} position={[0, 1.057, -0.664]} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-1.482, 0, 0.946]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_74.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-3.507, 0, 0.946]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_81.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[0.545, 0, 0.946]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_88.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[0.527, 0, -0.771]} scale={0.58}>
        <mesh geometry={nodes.Object_95.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.shelf} position={[0, 1.057, -0.664]} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-1.498, 0, -0.771]} scale={0.58}>
        <mesh geometry={nodes.Object_104.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.shelf} position={[0, 1.057, -0.664]} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[0.527, 0, -1.54]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_113.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-1.498, 0, -1.54]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_120.geometry} material={materials.shelf} position={[0, 0.238, 0]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.shelf} position={[0, 0.075, -0.181]} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.shelf} position={[0, 0.978, 0]} />
      </group>
      <group position={[-3.637, 0, 3.456]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_127.geometry} material={materials.shelf} position={[-3.552, 0.238, 0.296]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.shelf} position={[0, 0.238, 0.275]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.shelf} position={[0, 1.057, -0.389]} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.shelf} position={[0, 0.075, 0.094]} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.shelf} position={[0, 0.978, 0.275]} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.shelf} position={[-3.552, 1.057, -0.368]} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.shelf} position={[-3.552, 0.075, 0.115]} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.shelf} position={[-3.552, 0.978, 0.296]} />
      </group>
      <group position={[-5.169, 0, -2.164]} scale={[-0.58, 0.58, 0.58]}>
        <mesh geometry={nodes.Object_144.geometry} material={materials.shelf} position={[0, 0.238, 0.11]} scale={[0.531, 1, 1]} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.shelf} position={[0, 0.075, -0.071]} />
        <mesh geometry={nodes.Object_148.geometry} material={materials.shelf} position={[0, 0.978, 0.11]} />
      </group>
      <group position={[1.784, 0, 1.353]}>
        <mesh geometry={nodes.Object_150.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.merch} position={[0.253, 0.331, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_154.geometry} material={materials.merch} position={[0.107, 0.944, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_156.geometry} material={materials.gradient} position={[-0.102, 1.34, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.12, 0.379, 0.379]} />
      </group>
      <group position={[1.784, 0, -1.146]}>
        <mesh geometry={nodes.Object_158.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_160.geometry} material={materials.merch} position={[0.253, 0.331, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.merch} position={[0.107, 0.944, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_164.geometry} material={materials['gradient.001']} position={[-0.102, 1.34, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.12, 0.379, 0.379]} />
      </group>
      <group position={[-2.77, -0.002, -1.169]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_166.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.merch} position={[0.253, 0.331, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.merch} position={[0.107, 0.944, 0.24]} scale={[0.055, 0.137, 0.105]} />
        <mesh geometry={nodes.Object_172.geometry} material={materials.gradient} position={[-0.102, 1.34, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.12, 0.379, 0.379]} />
      </group>
      <group position={[-1.604, 0, -3.551]} scale={1.146}>
        <mesh geometry={nodes.Object_174.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_178.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_180.geometry} material={materials.fridge} position={[0.54, 0.958, 0.394]} scale={[1, 2.044, 0.569]} />
        <mesh geometry={nodes.Object_182.geometry} material={materials.fridge} position={[0, 0.406, -0.036]} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_186.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_188.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_190.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_192.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_194.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_196.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_198.geometry} material={materials.soda} position={[-0.456, 1.714, 0.257]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_200.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_202.geometry} material={materials.soda} position={[-0.456, 1.714, 0.257]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_204.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_206.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_208.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_210.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_212.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_214.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_216.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_218.geometry} material={materials.soda} position={[-0.453, 1.707, 0.249]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_220.geometry} material={materials.soda} position={[-0.453, 1.707, 0.249]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_222.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_224.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_226.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_228.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_230.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_232.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_234.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_236.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_238.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_240.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_242.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_244.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_246.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_248.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_250.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_252.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_254.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_256.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_258.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_260.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_262.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_264.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_266.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_268.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_270.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_272.geometry} material={materials.soda} position={[-0.464, 1.708, 0.241]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_274.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_276.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_278.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_280.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_282.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_284.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_286.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_288.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_290.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_292.geometry} material={materials.soda} position={[-0.444, 1.712, 0.245]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_294.geometry} material={materials.soda} position={[-0.452, 1.712, 0.244]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_296.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_298.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_300.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
      </group>
      <group position={[-0.27, 0, -3.551]} scale={1.146}>
        <mesh geometry={nodes.Object_302.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_304.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_306.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_308.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_312.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_314.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_316.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_318.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_320.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_322.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_324.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_326.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_328.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_330.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.soda} position={[-0.446, 1.702, 0.252]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_334.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_336.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_338.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_342.geometry} material={materials.soda} position={[-0.446, 1.702, 0.252]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_344.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_346.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_348.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_350.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_352.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_354.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_356.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_358.geometry} material={materials.soda} position={[-0.446, 0.462, 0.258]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_360.geometry} material={materials.soda} position={[-0.446, 0.462, 0.258]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_362.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_364.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_366.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_368.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_370.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_372.geometry} material={materials.soda} position={[-0.446, 0.47, 0.192]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_374.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_376.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_378.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_380.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_382.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_384.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_386.geometry} material={materials.soda} position={[-0.446, 0.773, 0.254]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_388.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_390.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_392.geometry} material={materials.soda} position={[-0.446, 0.773, 0.254]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_394.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_396.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_398.geometry} material={materials.soda} position={[-0.446, 0.784, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_400.geometry} material={materials.soda} position={[-0.446, 0.773, 0.254]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_402.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_404.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_406.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_408.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_410.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_412.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_414.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_416.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_418.geometry} material={materials.soda} position={[-0.448, 1.082, 0.256]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_420.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_422.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_424.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_426.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_428.geometry} material={materials.soda} position={[-0.446, 1.088, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_430.geometry} material={materials.soda} position={[-0.448, 1.082, 0.256]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_432.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_434.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_436.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_438.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_440.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_442.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_444.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_446.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_448.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_450.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_452.geometry} material={materials.soda} position={[-0.446, 1.393, 0.251]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_454.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_456.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_458.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_460.geometry} material={materials.soda} position={[-0.446, 1.398, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_462.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_464.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_466.geometry} material={materials.fridge} position={[0.54, 0.958, 0.394]} scale={[1, 2.044, 0.569]} />
        <mesh geometry={nodes.Object_468.geometry} material={materials.fridge} position={[0, 0.406, -0.036]} />
      </group>
      <group position={[1.067, 0, -3.551]} scale={1.146}>
        <mesh geometry={nodes.Object_470.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_472.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_474.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_476.geometry} material={materials.fridge} position={[0.54, 0.958, 0.394]} scale={[1, 2.044, 0.569]} />
        <mesh geometry={nodes.Object_478.geometry} material={materials.fridge} position={[0, 0.406, -0.036]} />
        <mesh geometry={nodes.Object_480.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_482.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_484.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_486.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_488.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_490.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_492.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_494.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_496.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_498.geometry} material={materials.soda} position={[-0.454, 1.714, 0.257]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_500.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_502.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_504.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_506.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_508.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_510.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_512.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_514.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_516.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_518.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_520.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_522.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_524.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_526.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_528.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_530.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_532.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_534.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_536.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_538.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_540.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_542.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_544.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_546.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_548.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_550.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_552.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_554.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_556.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_558.geometry} material={materials.soda} position={[-0.454, 1.709, 0.264]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_560.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_562.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_564.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_566.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_568.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_570.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_572.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_574.geometry} material={materials.soda} position={[-0.454, 1.706, 0.265]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_576.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_578.geometry} material={materials.soda} position={[-0.454, 1.706, 0.265]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_580.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_582.geometry} material={materials.soda} position={[-0.454, 1.706, 0.265]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_584.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_586.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_588.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_590.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_592.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_594.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_596.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_598.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_600.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_602.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_604.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_606.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_608.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_610.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_612.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
        <mesh geometry={nodes.Object_614.geometry} material={materials.soda} position={[-0.454, 1.721, 0.168]} rotation={[0.081, 0, 0]} scale={0.818} />
      </group>
      <group position={[2.4, 0, -3.551]} scale={1.146}>
        <mesh geometry={nodes.Object_616.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_618.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_620.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_622.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_624.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_626.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_628.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_630.geometry} material={materials.soda} position={[-0.446, 1.703, 0.251]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_632.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_634.geometry} material={materials.soda} position={[-0.446, 1.703, 0.251]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_636.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_638.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_640.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_642.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_644.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_646.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_648.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_650.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_652.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_654.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_656.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_658.geometry} material={materials.soda} position={[-0.446, 1.739, 0.27]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_660.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_662.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_664.geometry} material={materials.soda} position={[-0.446, 1.739, 0.27]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_666.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_668.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_670.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_672.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_674.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_676.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_678.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_680.geometry} material={materials.soda} position={[-0.446, 1.705, 0.227]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_682.geometry} material={materials.soda} position={[-0.446, 1.703, 0.252]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_684.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_686.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_688.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_690.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_692.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_694.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_696.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_698.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_700.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_702.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_704.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_706.geometry} material={materials.soda} position={[-0.446, 1.709, 0.261]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_708.geometry} material={materials.soda} position={[-0.446, 1.709, 0.261]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_710.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_712.geometry} material={materials.soda} position={[-0.446, 1.709, 0.261]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_714.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_716.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_718.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_720.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_722.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_724.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_726.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_728.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_730.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_732.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_734.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_736.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_738.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_740.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_742.geometry} material={materials.soda} position={[-0.446, 1.709, 0.254]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_744.geometry} material={materials.soda} position={[-0.446, 1.709, 0.254]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_746.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_748.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_750.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_752.geometry} material={materials.soda} position={[-0.446, 1.715, 0.187]} rotation={[0.09, 0, 0]} scale={0.433} />
        <mesh geometry={nodes.Object_754.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_756.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_758.geometry} material={materials.fridge} position={[0.54, 0.958, 0.394]} scale={[1, 2.044, 0.569]} />
        <mesh geometry={nodes.Object_760.geometry} material={materials.fridge} position={[0, 0.406, -0.036]} />
      </group>
      <group position={[4.965, 1.101, 3.438]} rotation={[-Math.PI, 0.585, -Math.PI]} scale={[0.017, 0.106, 0.299]}>
        <mesh geometry={nodes.Object_796.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_798.geometry} material={materials.merch} position={[0.985, 1.635, -0.019]} rotation={[0, -Math.PI / 2, 0]} scale={[3.345, 9.414, 59.008]} />
        <mesh geometry={nodes.Object_800.geometry} material={materials.merch} position={[13.964, -0.581, 0.426]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.576, 0.267, 0.095]} />
      </group>
      <group position={[4.86, 1.103, 2.847]} scale={[0.066, 0.108, 0.066]}>
        <mesh geometry={nodes.Object_802.geometry} material={materials.merch} />
        <mesh geometry={nodes.Object_804.geometry} material={materials.merch} position={[0.441, 1.004, -0.215]} rotation={[3.137, 0.002, -3.107]} scale={[0.102, 1.574, 0.102]} />
        <mesh geometry={nodes.Object_806.geometry} material={materials.merch} position={[0.582, 0.961, 0.147]} rotation={[-2.974, 0.024, -2.896]} scale={[0.101, 1.667, 0.101]} />
        <mesh geometry={nodes.Object_808.geometry} material={materials.merch} position={[0.124, 1.004, -0.472]} rotation={[3.126, -0.004, -3.104]} scale={[0.102, 1.574, 0.102]} />
        <mesh geometry={nodes.Object_810.geometry} material={materials.merch} position={[0.289, 1, -0.661]} rotation={[3.022, 0.001, 3.14]} scale={[0.102, 1.587, 0.102]} />
        <mesh geometry={nodes.Object_812.geometry} material={materials.merch} position={[-0.178, 0.926, -0.019]} scale={[0.102, 1.572, 0.102]} />
        <mesh geometry={nodes.Object_814.geometry} material={materials.merch} position={[-0.717, 0.986, 0]} rotation={[-3.111, 0.025, 2.927]} scale={[0.101, 1.621, 0.102]} />
        <mesh geometry={nodes.Object_816.geometry} material={materials.merch} position={[0.156, 0.955, 0.022]} rotation={[-2.995, 0.03, -2.869]} scale={[0.1, 1.675, 0.102]} />
        <mesh geometry={nodes.Object_818.geometry} material={materials.merch} position={[0.408, 0.96, 0.032]} rotation={[-3.001, 0.022, -2.877]} scale={[0.1, 1.668, 0.102]} />
        <mesh geometry={nodes.Object_820.geometry} material={materials.merch} position={[0.383, 0.973, 0.575]} rotation={[-2.679, -0.894, -2.977]} scale={[0.102, 1.65, 0.1]} />
        <mesh geometry={nodes.Object_822.geometry} material={materials.merch} position={[0.036, 0.996, 0.569]} rotation={[-2.839, -0.965, -3.023]} scale={[0.102, 1.602, 0.101]} />
      </group>
      <group position={[-6.448, 1.702, 1.518]} rotation={[0, Math.PI / 2, 0]} scale={1.731}>
        <mesh geometry={nodes.Object_848.geometry} material={materials.merch} />
        <mesh geometry={nodes.Object_850.geometry} material={materials.pastry} position={[-0.13, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_852.geometry} material={materials.pastry} position={[0.063, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_854.geometry} material={materials.pastry} position={[0.253, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_856.geometry} material={materials.pastry} position={[-0.326, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_858.geometry} material={materials.pastry} position={[-0.336, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_860.geometry} material={materials.pastry} position={[-0.143, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_862.geometry} material={materials.pastry} position={[0.047, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_864.geometry} material={materials.pastry} position={[-0.336, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_866.geometry} material={materials.pastry} position={[-0.14, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_868.geometry} material={materials.pastry} position={[0.051, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_870.geometry} material={materials.pastry} position={[0.246, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_872.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_874.geometry} material={materials.fridge} position={[0.004, -0.188, 0.216]} scale={[0.006, 0.049, 0.006]} />
        <mesh geometry={nodes.Object_876.geometry} material={materials.fridge} position={[0, -0.423, -0.081]} rotation={[-Math.PI, 0, 0]} scale={[-0.656, 0.008, 0.207]} />
        <mesh geometry={nodes.Object_878.geometry} material={materials.pastry} position={[0.244, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
      </group>
      <group position={[-6.448, 1.702, -0.653]} rotation={[0, Math.PI / 2, 0]} scale={1.731}>
        <mesh geometry={nodes.Object_880.geometry} material={materials.merch} />
        <mesh geometry={nodes.Object_882.geometry} material={materials.pastry} position={[-0.326, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_884.geometry} material={materials.pastry} position={[-0.13, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_886.geometry} material={materials.pastry} position={[0.063, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_888.geometry} material={materials.pastry} position={[0.253, -0.412, 0.053]} rotation={[0.156, 0, 0]} scale={1.029} />
        <mesh geometry={nodes.Object_890.geometry} material={materials.pastry} position={[-0.336, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_892.geometry} material={materials.pastry} position={[-0.143, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_894.geometry} material={materials.pastry} position={[0.047, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_896.geometry} material={materials.pastry} position={[0.244, -0.215, 0.071]} rotation={[0.174, 0, 0]} scale={0.03} />
        <mesh geometry={nodes.Object_898.geometry} material={materials.pastry} position={[-0.336, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_900.geometry} material={materials.pastry} position={[-0.14, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_902.geometry} material={materials.pastry} position={[0.051, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_904.geometry} material={materials.pastry} position={[0.246, -0.004, 0.097]} rotation={[0.156, 0, 0]} scale={1.182} />
        <mesh geometry={nodes.Object_906.geometry} material={materials.glass} />
        <mesh geometry={nodes.Object_908.geometry} material={materials.fridge} position={[0.004, -0.188, 0.216]} scale={[0.006, 0.049, 0.006]} />
        <mesh geometry={nodes.Object_910.geometry} material={materials.fridge} position={[0, -0.423, -0.081]} rotation={[-Math.PI, 0, 0]} scale={[-0.656, 0.008, 0.207]} />
      </group>
      <group position={[-6.139, 0.145, 0.429]} scale={1.146}>
        <mesh geometry={nodes.Object_912.geometry} material={materials.fridge} />
        <mesh geometry={nodes.Object_914.geometry} material={materials.fridge} position={[0.076, 0.685, 0]} />
      </group>
      <group position={[-3.891, 0, -4.487]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.055, 1.146, 0.055]}>
        <mesh geometry={nodes.Object_916.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_918.geometry} material={materials.shelf} position={[0, 0.17, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[30.391, 0.022, 7.421]} />
      </group>
      <group position={[-0.428, 0, -4.487]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.055, 1.146, 0.055]}>
        <mesh geometry={nodes.Object_920.geometry} material={materials.shelf} />
        <mesh geometry={nodes.Object_922.geometry} material={materials.shelf} position={[0, 0.17, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[30.391, 0.022, 7.421]} />
      </group>
      <group position={[-5.728, 3.027, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_978.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_979.geometry} material={materials.fridge} />
      </group>
      <group position={[-3.437, 3.027, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_981.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_982.geometry} material={materials.fridge} />
      </group>
      <group position={[-1.146, 3.027, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_984.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_985.geometry} material={materials.fridge} />
      </group>
      <group position={[1.146, 3.027, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_987.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_988.geometry} material={materials.fridge} />
      </group>
      <group position={[3.437, 3.027, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_990.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_991.geometry} material={materials.fridge} />
      </group>
      <group position={[-5.728, 3.027, 2.693]} scale={1.146}>
        <mesh geometry={nodes.Object_993.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_994.geometry} material={materials.fridge} />
      </group>
      <group position={[-3.437, 3.027, 2.693]} scale={1.146}>
        <mesh geometry={nodes.Object_996.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_997.geometry} material={materials.fridge} />
      </group>
      <group position={[-1.146, 3.027, 2.693]} scale={1.146}>
        <mesh geometry={nodes.Object_999.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1000.geometry} material={materials.fridge} />
      </group>
      <group position={[1.146, 3.027, 2.693]} scale={1.146}>
        <mesh geometry={nodes.Object_1002.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1003.geometry} material={materials.fridge} />
      </group>
      <group position={[3.437, 3.027, 2.693]} scale={1.146}>
        <mesh geometry={nodes.Object_1005.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1006.geometry} material={materials.fridge} />
      </group>
      <group position={[-1.146, 3.027, -2.082]} scale={1.146}>
        <mesh geometry={nodes.Object_1008.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1009.geometry} material={materials.fridge} />
      </group>
      <group position={[1.146, 3.027, -2.082]} scale={1.146}>
        <mesh geometry={nodes.Object_1011.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1012.geometry} material={materials.fridge} />
      </group>
      <group position={[3.437, 3.027, -2.082]} scale={1.146}>
        <mesh geometry={nodes.Object_1014.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1015.geometry} material={materials.fridge} />
      </group>
      <group position={[-5.473, 3.027, -3.189]} scale={1.146}>
        <mesh geometry={nodes.Object_1017.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1018.geometry} material={materials.fridge} />
      </group>
      <group position={[5.753, 3.027, -2.695]} rotation={[0, Math.PI / 2, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_1020.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1021.geometry} material={materials.fridge} />
      </group>
      <group position={[5.676, 2.562, 1.988]} rotation={[0, Math.PI / 2, 0]} scale={1.146}>
        <mesh geometry={nodes.Object_1023.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1024.geometry} material={materials.fridge} />
      </group>
      <group position={[4.228, 3.386, -5.288]} scale={1.146}>
        <mesh geometry={nodes.Object_1026.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1027.geometry} material={materials.fridge} />
      </group>
      <group position={[0.161, 3.386, -5.288]} scale={1.146}>
        <mesh geometry={nodes.Object_1029.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1030.geometry} material={materials.fridge} />
      </group>
      <group position={[-3.865, 3.386, -5.288]} scale={1.146}>
        <mesh geometry={nodes.Object_1032.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_1033.geometry} material={materials.fridge} />
      </group>
      <group position={[-0.006, 0, 3.748]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_1046.geometry} material={materials.building} skeleton={nodes.Object_1046.skeleton} />
        <skinnedMesh geometry={nodes.Object_1048.geometry} material={materials.building} skeleton={nodes.Object_1048.skeleton} />
        <skinnedMesh geometry={nodes.Object_1050.geometry} material={materials.glass} skeleton={nodes.Object_1050.skeleton} />
        <skinnedMesh geometry={nodes.Object_1052.geometry} material={materials.glass} skeleton={nodes.Object_1052.skeleton} />
        <skinnedMesh geometry={nodes.Object_1054.geometry} material={materials.outline} skeleton={nodes.Object_1054.skeleton} />
        <skinnedMesh geometry={nodes.Object_1056.geometry} material={materials.outline} skeleton={nodes.Object_1056.skeleton} />
      </group>
      <group position={[-4.029, 0, -3.238]}>
        <primitive object={nodes.GLTF_created_1_rootJoint} />
        <skinnedMesh geometry={nodes.Object_1063.geometry} material={materials.building} skeleton={nodes.Object_1063.skeleton} />
        <skinnedMesh geometry={nodes.Object_1065.geometry} material={materials.outline} skeleton={nodes.Object_1065.skeleton} />
        <mesh geometry={nodes.Object_1067.geometry} material={materials.building} />
        <mesh geometry={nodes.Object_1069.geometry} material={materials.outline} />
      </group>
      <group position={[4.302, 0.02, -3.948]}>
        <primitive object={nodes.GLTF_created_2_rootJoint} />
        <skinnedMesh geometry={nodes.Object_1075.geometry} material={materials.door} skeleton={nodes.Object_1075.skeleton} />
        <skinnedMesh geometry={nodes.Object_1079.geometry} material={materials.outline} skeleton={nodes.Object_1079.skeleton} />
        <mesh geometry={nodes.Object_1077.geometry} material={materials.door} position={[0, 1.194, 0]} />
        <mesh geometry={nodes.Object_1081.geometry} material={materials.outline} position={[0, 1.194, 0]} />
      </group>
      <group position={[5.25, 0.918, 0.377]}>
        <primitive object={nodes.GLTF_created_3_rootJoint} />
        <skinnedMesh geometry={nodes.Object_1087.geometry} material={materials.building} skeleton={nodes.Object_1087.skeleton} />
        <skinnedMesh geometry={nodes.Object_1089.geometry} material={materials.outline} skeleton={nodes.Object_1089.skeleton} />
      </group>
      <group position={[6.177, 0, -1.202]}>
        <primitive object={nodes.GLTF_created_4_rootJoint} />
        <skinnedMesh geometry={nodes.Object_1095.geometry} material={materials.outline} skeleton={nodes.Object_1095.skeleton} />
        <skinnedMesh geometry={nodes.Object_1097.geometry} material={materials.building} skeleton={nodes.Object_1097.skeleton} />
        <mesh geometry={nodes.Object_1099.geometry} material={materials.building} position={[-0.465, 0, 0]} />
        <mesh geometry={nodes.Object_1101.geometry} material={materials.building} position={[-0.465, 0, 0]} />
      </group>
      <mesh geometry={nodes.Object_12.geometry} material={materials.fridge} position={[-0.002, 2.897, 4.026]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.fridge} position={[-0.002, 2.874, 3.863]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.fridge} position={[1.12, 2.864, 3.849]} scale={[2.154, 0.859, 0.5]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.fridge} position={[-1.171, 2.864, 3.849]} scale={[2.154, 0.859, 0.5]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.fridge} position={[-0.056, 0, 2.858]} scale={1.146} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.merch} position={[4.895, 1.208, 2.875]} rotation={[-2.735, -0.943, -2.789]} scale={[0.007, 0.17, 0.007]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.fridge} position={[3.944, 0, 1.958]} rotation={[0, Math.PI / 2, 0]} scale={0.802} />
      <mesh geometry={nodes.Object_762.geometry} material={materials.merch} position={[-4.362, 1.305, -2.239]} />
      <mesh geometry={nodes.Object_764.geometry} material={materials.merch} position={[6.699, 1.035, 0.629]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_766.geometry} material={materials.merch} position={[6.699, 1.035, 1.39]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_768.geometry} material={materials.merch} position={[6.699, 1.318, 0.629]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_770.geometry} material={materials.merch} position={[6.699, 1.318, 1.39]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_772.geometry} material={materials.merch} position={[6.699, 1.615, 0.629]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_774.geometry} material={materials.merch} position={[6.699, 1.615, 1.39]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_776.geometry} material={materials.merch} position={[6.699, 1.898, 0.629]} />
      <mesh geometry={nodes.Object_778.geometry} material={materials.merch} position={[6.699, 1.898, 1.39]} />
      <mesh geometry={nodes.Object_780.geometry} material={materials.merch} position={[6.699, 1.035, 2.2]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_782.geometry} material={materials.merch} position={[6.699, 1.035, 2.961]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_784.geometry} material={materials.merch} position={[6.699, 1.318, 2.2]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_786.geometry} material={materials.merch} position={[6.699, 1.318, 2.961]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_788.geometry} material={materials.merch} position={[6.699, 1.615, 2.2]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_790.geometry} material={materials.merch} position={[6.699, 1.615, 2.961]} rotation={[0, 0, 0.147]} scale={[0.018, 0.049, 0.049]} />
      <mesh geometry={nodes.Object_792.geometry} material={materials.merch} position={[6.699, 1.898, 2.199]} />
      <mesh geometry={nodes.Object_794.geometry} material={materials.merch} position={[6.699, 1.898, 2.96]} />
      <mesh geometry={nodes.Object_824.geometry} material={materials.shelf} position={[6.75, 0.963, 1.336]} rotation={[0, -Math.PI / 2, 0]} scale={[1.108, 1.146, 0.524]} />
      <mesh geometry={nodes.Object_826.geometry} material={materials.poster_1} position={[3.232, 1.482, 3.893]} rotation={[Math.PI / 2, 0, 0]} scale={2.212} />
      <mesh geometry={nodes.Object_828.geometry} material={materials.poster_2} position={[5.648, 1.509, 3.893]} rotation={[Math.PI / 2, 0, 0]} scale={2.264} />
      <mesh geometry={nodes.Object_830.geometry} material={materials.poster_1} position={[-5.639, 1.482, 3.893]} rotation={[Math.PI / 2, 0, 0]} scale={2.212} />
      <mesh geometry={nodes.Object_832.geometry} material={materials.poster_2} position={[-3.177, 1.509, 3.893]} rotation={[Math.PI / 2, 0, 0]} scale={2.264} />
      <mesh geometry={nodes.Object_834.geometry} material={materials.poster_wide} position={[4.587, 0.471, 1.979]} />
      <mesh geometry={nodes.Object_836.geometry} material={materials.Book} position={[-2.84, 0.885, 3.628]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_838.geometry} material={materials.Book} position={[-2.84, 1.371, 3.691]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_840.geometry} material={materials.Book} position={[-2.84, 0.388, 3.563]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_842.geometry} material={materials.Book} position={[-4.901, 0.388, 3.722]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_844.geometry} material={materials.Book} position={[-4.918, 0.885, 3.615]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_846.geometry} material={materials.Book} position={[-4.918, 1.371, 3.678]} rotation={[0.129, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_924.geometry} material={materials.cardboard_box} position={[0.733, 0.47, -4.55]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_926.geometry} material={materials.cardboard_box} position={[-0.338, 0.47, -4.55]} rotation={[0, -0.127, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_928.geometry} material={materials.cardboard_box} position={[0.654, 1.06, -4.55]} rotation={[-Math.PI, 1.529, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_930.geometry} material={materials.cardboard_box} position={[-1.681, 0.47, -4.55]} rotation={[0, 0.416, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_932.geometry} material={materials.cardboard_box} position={[-0.276, 1.06, -4.55]} rotation={[-Math.PI, 1.485, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_934.geometry} material={materials.cardboard_box} position={[-1.31, 1.06, -4.55]} rotation={[0, 1.337, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_936.geometry} material={materials.cardboard_box} position={[-1.374, 1.665, -4.55]} rotation={[0, -0.036, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_938.geometry} material={materials.cardboard_box} position={[-0.341, 1.665, -4.55]} rotation={[0, 0.91, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_940.geometry} material={materials.cardboard_box} position={[0.562, 1.665, -4.55]} rotation={[-Math.PI, 1.311, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_942.geometry} material={materials.cardboard_box} position={[-2.707, 0.47, -4.55]} rotation={[0, 0.327, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_944.geometry} material={materials.cardboard_box} position={[-3.815, 0.47, -4.55]} rotation={[0, -0.127, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_946.geometry} material={materials.cardboard_box} position={[-2.668, 1.06, -4.55]} rotation={[-Math.PI, 1.529, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_948.geometry} material={materials.cardboard_box} position={[-5.003, 0.47, -4.55]} rotation={[0, 0.416, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_950.geometry} material={materials.cardboard_box} position={[-3.598, 1.06, -4.55]} rotation={[-Math.PI, 1.485, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_952.geometry} material={materials.cardboard_box} position={[-4.633, 1.06, -4.55]} rotation={[-Math.PI, 0.615, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_954.geometry} material={materials.cardboard_box} position={[-4.697, 1.665, -4.55]} rotation={[0, -0.036, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_956.geometry} material={materials.cardboard_box} position={[-3.663, 1.665, -4.55]} rotation={[0, 0.403, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_958.geometry} material={materials.cardboard_box} position={[-2.76, 1.665, -4.55]} rotation={[-Math.PI, 1.121, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_960.geometry} material={materials.cardboard_box} position={[-5.26, 0.25, -6.165]} rotation={[0, 1.527, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_962.geometry} material={materials.cardboard_box} position={[-5.288, 0.751, -6.134]} rotation={[-Math.PI, 1.406, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_964.geometry} material={materials.cardboard_box} position={[-5.314, 1.251, -6.117]} rotation={[0, 1.332, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_966.geometry} material={materials.cardboard_box} position={[-5.195, 0.25, -5.333]} rotation={[-Math.PI, 0.242, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_968.geometry} material={materials.cardboard_box} position={[-4.4, 0.25, -6.228]} rotation={[0, 1.068, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_970.geometry} material={materials.cardboard_box} position={[-4.426, 0.751, -6.214]} rotation={[-Math.PI, 1.436, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_972.geometry} material={materials.cardboard_box} position={[-3.547, 0.25, -6.221]} rotation={[-Math.PI, 1.469, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_974.geometry} material={materials.cardboard_box} position={[4.947, 0.25, -6.221]} rotation={[0, 1.231, 0]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_976.geometry} material={materials.cardboard_box} position={[4.995, 0.25, -4.856]} rotation={[-Math.PI, 1.319, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_1035.geometry} material={materials.toilet} position={[-6.348, 0.049, -3.258]} scale={[0.264, 0.053, 0.224]} />
      <mesh geometry={nodes.Object_1037.geometry} material={materials.fridge} position={[-5.181, 0.049, -3.71]} scale={[0.094, 0.048, 0.094]} />
      <mesh geometry={nodes.Object_1039.geometry} material={materials.fridge} position={[-5.174, 1.611, -3.901]} scale={[0.325, 0.38, 0.045]} />
      <mesh geometry={nodes.Object_1041.geometry} material={materials.door} position={[3.437, 0, -6.807]} />
      <mesh geometry={nodes.Object_1104.geometry} material={materials.mart} position={[0.165, 3.952, 4.265]} rotation={[Math.PI / 2, 0, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_1106.geometry} material={materials.beverage} position={[0.316, 2.62, -3.137]} scale={1.146} />
      <mesh geometry={nodes.Object_1108.geometry} material={materials.checkout} position={[4.578, 2.664, 2.042]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.392, 0.392, 0.392]} />
      <mesh geometry={nodes.Object_1110.geometry} material={materials.resetroom} position={[-5.386, 2.646, -2.445]} rotation={[Math.PI / 2, 0, 0]} scale={0.356} />
      <mesh geometry={nodes.Object_1112.geometry} material={materials.welcome} position={[-0.056, 0, 2.858]} scale={0.353} />
      <mesh geometry={nodes.Object_1114.geometry} material={materials.floor} scale={1.146} />
      <mesh geometry={nodes.Object_1116.geometry} material={materials.front_sign} position={[-4.537, 3.858, 3.96]} scale={1.146} />
      <mesh geometry={nodes.Object_1118.geometry} material={materials.building} scale={1.146} />
      <mesh geometry={nodes.Object_1120.geometry} material={materials.building} position={[-4.967, 0, -2.649]} scale={1.146} />
      <mesh geometry={nodes.Object_1122.geometry} material={materials.cieling} position={[0, 2.98, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_1124.geometry} material={materials.building} position={[4.823, 0.344, 2.67]} scale={[0.246, 0.345, 1.146]} />
      <mesh geometry={nodes.Object_1126.geometry} material={materials.building} position={[4.582, 0, -1.146]} scale={1.146} />
      <mesh geometry={nodes.Object_1128.geometry} material={materials.building} position={[0, 1.146, -5.138]} scale={1.146} />
      <mesh geometry={nodes.Object_1130.geometry} material={materials.glass} scale={1.146} />
      <mesh geometry={nodes.Object_1132.geometry} material={materials.building} position={[0.379, 2.683, -3.366]} scale={[2.685, 0.269, 0.598]} />
      <mesh geometry={nodes.Object_1134.geometry} material={materials.backroom_floor} position={[0, 1.146, -5.138]} scale={1.146} />
      <mesh geometry={nodes.Object_1136.geometry} material={materials.building} position={[0, 1.146, -5.155]} scale={1.146} />
      <mesh geometry={nodes.Object_1138.geometry} material={materials.building} scale={1.146} />
      <mesh geometry={nodes.Object_1140.geometry} material={materials.gradient} position={[0.002, 3.824, -0.014]} scale={[1.152, 1.039, 1.152]} />
      <mesh geometry={nodes.Object_1142.geometry} material={materials.cieling} position={[0, 1.146, -5.138]} scale={1.146} />
      <mesh geometry={nodes.Object_1144.geometry} material={materials.building} position={[1.912, 0, -0.025]} />
      <mesh geometry={nodes.Object_1146.geometry} material={materials.glass} position={[1.912, 0, -0.025]} />
      <mesh geometry={nodes.Object_1148.geometry} material={materials.outline} />
      <mesh geometry={nodes.Object_1150.geometry} material={materials.outline} position={[-4.537, 3.858, 3.96]} />
      <mesh geometry={nodes.Object_1152.geometry} material={materials.outline} position={[0.545, 0.613, 1.331]} />
      <mesh geometry={nodes.Object_1154.geometry} material={materials.outline} position={[-4.362, 1.305, -2.239]} />
      <mesh geometry={nodes.Object_1156.geometry} material={materials.outline} position={[-2.84, 0.885, 3.628]} />
      <mesh geometry={nodes.Object_1158.geometry} material={materials.outline} position={[-6.052, 0.93, 0.429]} />
      <mesh geometry={nodes.Object_1160.geometry} material={materials.outline} position={[-0.27, 0, -3.551]} scale={1.146} />
      <mesh geometry={nodes.Object_1162.geometry} material={materials.outline} position={[0.379, 2.683, -3.366]} scale={[2.685, 0.269, 0.598]} />
      <mesh geometry={nodes.Object_1164.geometry} material={materials.outline} position={[4.823, 0.344, 2.67]} scale={[0.246, 0.345, 1.146]} />
      <mesh geometry={nodes.Object_1166.geometry} material={materials.outline} position={[4.717, 1.225, 1.065]} rotation={[0, 1.429, 0]} scale={[0.286, 0.208, 0.171]} />
      <mesh geometry={nodes.Object_1168.geometry} material={materials.outline} position={[6.75, 0.963, 1.336]} rotation={[0, -Math.PI / 2, 0]} scale={[1.108, 1.146, 0.524]} />
      <mesh geometry={nodes.Object_1170.geometry} material={materials.outline} position={[5.687, 0.773, 3.349]} scale={1.146} />
      <mesh geometry={nodes.Object_1172.geometry} material={materials.outline} position={[3.984, 0, 3.771]} scale={1.146} />
      <mesh geometry={nodes.Object_1174.geometry} material={materials.outline} position={[-3.891, 0.194, -4.487]} scale={[1.678, 0.025, 0.41]} />
      <mesh geometry={nodes.Object_1176.geometry} material={materials.outline} position={[-6.348, 0.049, -3.258]} scale={[0.264, 0.053, 0.224]} />
      <mesh geometry={nodes.Object_1178.geometry} material={materials.outline} position={[0, 1.146, -5.138]} scale={1.146} />
      <mesh geometry={nodes.Object_1180.geometry} material={materials.outline} scale={1.146} />
      <mesh geometry={nodes.Object_1182.geometry} material={materials.outline} position={[3.437, 3.027, 0]} scale={1.146} />
      <mesh geometry={nodes.Object_1184.geometry} material={materials.outline} position={[3.437, 0, -6.807]} />
      <mesh geometry={nodes.Object_1186.geometry} material={materials.outline} position={[0.562, 1.665, -4.55]} rotation={[-Math.PI, 1.311, -Math.PI]} scale={[0.374, 0.25, 0.288]} />
      <mesh geometry={nodes.Object_1188.geometry} material={materials.outline} position={[4.889, 1.212, 2.833]} rotation={[3.137, 0.002, -3.111]} scale={[0.007, 0.17, 0.007]} />
      <mesh geometry={nodes.Object_1190.geometry} material={materials.outline} position={[4.947, 1.275, 3.434]} rotation={[1.497, 0.111, -0.981]} scale={0.118} />
      <mesh geometry={nodes.Object_1192.geometry} material={materials.outline} position={[2.037, 0.331, 1.593]} />
      <mesh geometry={nodes.Object_1194.geometry} material={materials.outline} position={[2.037, 0.331, -0.906]} />
      <mesh geometry={nodes.Object_1196.geometry} material={materials.outline} position={[-3.023, 0.329, -1.409]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_1198.geometry} material={materials.outline} position={[-4.967, 0, -2.649]} />
      <mesh geometry={nodes.Object_1200.geometry} material={materials.outline} position={[4.582, 0, -1.146]} scale={1.146} />
      <mesh geometry={nodes.Object_1202.geometry} material={materials.outline} position={[1.912, 0, -0.025]} />
      <mesh geometry={nodes.Object_1204.geometry} material={materials.outline} position={[-0.056, 0, 2.858]} scale={1.146} />
      <mesh geometry={nodes.Object_1206.geometry} material={materials.outline} position={[3.944, 0, 1.958]} rotation={[0, Math.PI / 2, 0]} scale={0.802} />
      <mesh geometry={nodes.Object_1208.geometry} material={materials.outline} position={[3.293, 0, 3.771]} scale={1.146} />
    </group>
  )
}