/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: Hugo Armando Villadiego A (https://sketchfab.com/HugoVilladiego)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/restaurant-street-5ecfaba4569643279ffe9e34c8655a3d
Title: Restaurant Street
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Restaurant(props) {
  const { nodes, materials } = useGLTF(import.meta.env.VITE_S3_URL + 'Map/Restaurant/scene.gltf')

  useEffect(() => {
    if (props.onLoaded) {
      props.onLoaded();
    }
  }, [props, props.onLoaded]);

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-251.669, 0, -333.528]}>
          <mesh geometry={nodes.pCube47_silla1_0_1.geometry} material={materials.silla1} position={[-863.667, 0, -223.273]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube26_silla1_0_1.geometry} material={materials.silla1} position={[-8.673, 0, 0]} />
          <mesh geometry={nodes.pCylinder1_mesa1_0_1.geometry} material={materials.mesa1} position={[-318.077, 0, 91.261]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.pCylinder2_sombrilla1_0_1.geometry} material={materials.sombrilla1} />
          <mesh geometry={nodes.pCube45_silla1_0_1.geometry} material={materials.silla1} position={[199.534, 0, -868.82]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube46_silla1_0_1.geometry} material={materials.silla1} position={[-658.889, 0, -1065.572]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[-5.72, 0, -499.401]}>
          <mesh geometry={nodes.pCube47_silla1_0_2.geometry} material={materials.silla1} position={[-863.667, 0, -223.273]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube26_silla1_0_2.geometry} material={materials.silla1} position={[-8.673, 0, 0]} />
          <mesh geometry={nodes.pCylinder1_mesa1_0_2.geometry} material={materials.mesa1} position={[-318.077, 0, 91.261]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.pCylinder2_sombrilla1_0_2.geometry} material={materials.sombrilla1} />
          <mesh geometry={nodes.pCube45_silla1_0_2.geometry} material={materials.silla1} position={[199.534, 0, -868.82]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube46_silla1_0_2.geometry} material={materials.silla1} position={[-658.889, 0, -1065.572]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[-234.51, 0, -688.153]}>
          <mesh geometry={nodes.pCube47_silla1_0_3.geometry} material={materials.silla1} position={[-863.667, 0, -223.273]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube26_silla1_0_3.geometry} material={materials.silla1} position={[-8.673, 0, 0]} />
          <mesh geometry={nodes.pCylinder1_mesa1_0_3.geometry} material={materials.mesa1} position={[-318.077, 0, 91.261]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.pCylinder2_sombrilla1_0_3.geometry} material={materials.sombrilla1} />
          <mesh geometry={nodes.pCube45_silla1_0_3.geometry} material={materials.silla1} position={[199.534, 0, -868.82]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube46_silla1_0_3.geometry} material={materials.silla1} position={[-658.889, 0, -1065.572]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[-234.51, 0, -968.42]}>
          <mesh geometry={nodes.pCube47_silla1_0_4.geometry} material={materials.silla1} position={[-863.667, 0, -223.273]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube26_silla1_0_4.geometry} material={materials.silla1} position={[-8.673, 0, 0]} />
          <mesh geometry={nodes.pCylinder1_mesa1_0_4.geometry} material={materials.mesa1} position={[-318.077, 0, 91.261]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.pCylinder2_sombrilla1_0_4.geometry} material={materials.sombrilla1} />
          <mesh geometry={nodes.pCube45_silla1_0_4.geometry} material={materials.silla1} position={[199.534, 0, -868.82]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube46_silla1_0_4.geometry} material={materials.silla1} position={[-658.889, 0, -1065.572]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <group position={[40.038, 0, -859.745]}>
          <mesh geometry={nodes.pCube47_silla1_0_5.geometry} material={materials.silla1} position={[-863.667, 0, -223.273]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube26_silla1_0_5.geometry} material={materials.silla1} position={[-8.673, 0, 0]} />
          <mesh geometry={nodes.pCylinder1_mesa1_0_5.geometry} material={materials.mesa1} position={[-318.077, 0, 91.261]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.pCylinder2_sombrilla1_0_5.geometry} material={materials.sombrilla1} />
          <mesh geometry={nodes.pCube45_silla1_0_5.geometry} material={materials.silla1} position={[199.534, 0, -868.82]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pCube46_silla1_0_5.geometry} material={materials.silla1} position={[-658.889, 0, -1065.572]} rotation={[-Math.PI, 0, -Math.PI]} />
        </group>
        <mesh geometry={nodes.pCube34_esquina_restaurante_hava1_0.geometry} material={materials.esquina_restaurante_hava1} />
        <mesh geometry={nodes.pCube35_edificio_izq1_0.geometry} material={materials.edificio_izq1} position={[-22.682, 0, 0]} />
        <mesh geometry={nodes.pCube37_restaurante2_0.geometry} material={materials.restaurante2} />
        <mesh geometry={nodes.edififcio_ladrillo_edififcio_ladrillo1_0.geometry} material={materials.edififcio_ladrillo1} />
        <mesh geometry={nodes.pCube39_restaurante_hava_0.geometry} material={materials.restaurante_hava} />
        <mesh geometry={nodes.pCube40_restaurante_lado_hava_0.geometry} material={materials.restaurante_lado_hava} />
        <mesh geometry={nodes.pCube41_anden_der1_0.geometry} material={materials.anden_der1} />
        <mesh geometry={nodes.pCube42_anden_izq1_0.geometry} material={materials.anden_izq1} />
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} scale={1}/>
        {/*  */}
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1400, 1, 1]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[2800, 1, 1]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[2800, 1, 1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1, 1, 1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1, 1, 2800]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[2800, 1, 2800]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1400, 1, 1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1400, 1, 2800]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[2800, 1, 1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[-1400, 1, 1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[-2800, 1, 2800]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[-1400, 1, 2800]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[-1400, 1,-1400]}/>
        <mesh geometry={nodes.pPlane1_suelo1_0.geometry} material={materials.suelo1} position={[1, 1,-2800]}/>        
        {/*  */}
      </group>
      <group scale={0.01}>
        <group position={[0, 0, 200.322]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_1.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -168.558]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_2.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_1.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -361.382]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_3.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_2.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -509.493]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_4.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_3.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -956.62]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_5.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_4.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -1130.924]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_6.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_5.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -1524.351]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_7.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_6.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -1340.088]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_8.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_7.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -1683.714]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_9.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_8.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -2102.042]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_10.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_9.geometry} material={materials.matera1} />
        </group>
        <group position={[0, 0, -1907.819]}>
          <mesh geometry={nodes.pCube44_base_matera1_0_11.geometry} material={materials.base_matera1} />
          <mesh geometry={nodes.matera4_matera1_0_10.geometry} material={materials.matera1} />
        </group>
        <group position={[-1357.692, 11.779, 532.996]} rotation={[0, 1.488, 0]} scale={0.706}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_3.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_3.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_3.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_3.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_3.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_4.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_4.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_4.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_4.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_4.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_5.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_5.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_5.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_5.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_5.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[302.692, 0.57, 980.442]} rotation={[0, -1.1, 0]} scale={0.913}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_6.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_6.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_6.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_6.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_6.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_7.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_7.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_7.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_7.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_7.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_8.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_8.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_8.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_8.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_8.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[418.152, -39.458, 735.452]} rotation={[0, -1.033, 0]} scale={[1, 1.347, 1]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_9.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_9.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_9.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_9.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_9.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_10.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_10.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_10.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_10.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_10.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_11.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_11.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_11.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_11.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_11.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[116.671, -23.173, -251.946]} rotation={[0, -0.135, 0]} scale={[1, 1.634, 1]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_12.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_12.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_12.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_12.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_12.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_13.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_13.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_13.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_13.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_13.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_14.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_14.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_14.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_14.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_14.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[-619.687, 0, -775.01]} rotation={[0, 0.574, 0]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_15.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_15.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_15.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_15.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_15.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_16.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_16.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_16.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_16.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_16.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_17.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_17.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_17.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_17.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_17.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[0, 0, -946.463]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_18.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_18.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_18.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_18.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_18.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_19.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_19.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_19.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_19.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_19.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_20.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_20.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_20.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_20.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_20.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[0, 0, -1132.061]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_21.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_21.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_21.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_21.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_21.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_22.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_22.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_22.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_22.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_22.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_23.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_23.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_23.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_23.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_23.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[-740.866, -37.523, -1611.421]} rotation={[0, 0.677, 0]} scale={[1, 1.33, 1]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_24.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_24.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_24.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_24.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_24.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_25.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_25.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_25.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_25.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_25.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_26.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_26.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_26.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_26.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_26.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[-73.868, 14.304, -713.664]} rotation={[0, -0.723, 0]} scale={0.582}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_27.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_27.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_27.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_27.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_27.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_28.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_28.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_28.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_28.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_28.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_29.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_29.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_29.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_29.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_29.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[415.453, 0, -575.775]} rotation={[0, -1.048, 0]}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_30.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_30.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_30.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_30.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_30.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_31.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_31.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_31.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_31.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_31.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_32.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_32.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_32.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_32.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_32.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[-1132.095, 3.302, -1837.82]} rotation={[0, 1.108, 0]} scale={0.777}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_33.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_33.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_33.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_33.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_33.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_34.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_34.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_34.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_34.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_34.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_35.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_35.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_35.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_35.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_35.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <group position={[290.795, -23.066, -2132.509]} rotation={[0, -0.145, 0]} scale={1.188}>
          <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_36.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_36.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_36.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_36.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_36.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
            <mesh geometry={nodes.polySurface6_mata1_0_37.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_37.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_37.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_37.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_37.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
          <group position={[0, 0, -11.634]}>
            <mesh geometry={nodes.polySurface6_mata1_0_38.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
            <mesh geometry={nodes.polySurface4_mata1_0_38.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
            <mesh geometry={nodes.polySurface1_mata1_0_38.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface3_mata1_0_38.geometry} material={materials.mata1} />
            <mesh geometry={nodes.polySurface5_mata1_0_38.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
          </group>
        </group>
        <mesh geometry={nodes.poste_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[0, 0, -119.669]} />
        <mesh geometry={nodes.hidrante_hidrante1_0.geometry} material={materials.hidrante1} />
        <mesh geometry={nodes.pCube44_base_matera1_0.geometry} material={materials.base_matera1} />
        <mesh geometry={nodes.materamatera_matera1_0.geometry} material={materials.matera1} />
        <mesh geometry={nodes.Lp_15_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[0, 0, -1108.789]} />
        <mesh geometry={nodes.poste_aiStandardSurface11_0_1.geometry} material={materials.aiStandardSurface11} position={[0, 0, -675.521]} />
        <mesh geometry={nodes.poste1_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[0, 0, -1375.743]} />
        <mesh geometry={nodes.poste2_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[0, 0, 1215.692]} />
        <mesh geometry={nodes.poste3_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[0, 0, 484.228]} />
        <mesh geometry={nodes.poste4_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[398.14, 0.423, 566.813]} />
        <mesh geometry={nodes.poste5_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[398.14, 0.423, 1311.835]} />
        <mesh geometry={nodes.poste6_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[621.208, 0.423, -300.53]} />
        <mesh geometry={nodes.poste7_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[621.208, 0.423, -1148.913]} />
        <mesh geometry={nodes.poste8_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[621.208, 0.423, -1698.113]} />
        <mesh geometry={nodes.poste9_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} position={[398.14, 0.423, -60.342]} />
        <group position={[0, -44.74, -11.634]} scale={[1, 1.955, 1]}>
          <mesh geometry={nodes.polySurface6_mata1_0.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
          <mesh geometry={nodes.polySurface4_mata1_0.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
          <mesh geometry={nodes.polySurface1_mata1_0.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface3_mata1_0.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface5_mata1_0.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
        </group>
        <group position={[0, -24.958, -11.634]} scale={[1, 1.494, 1]}>
          <mesh geometry={nodes.polySurface6_mata1_0_1.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
          <mesh geometry={nodes.polySurface4_mata1_0_1.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
          <mesh geometry={nodes.polySurface1_mata1_0_1.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface3_mata1_0_1.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface5_mata1_0_1.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
        </group>
        <group position={[0, 0, -11.634]}>
          <mesh geometry={nodes.polySurface6_mata1_0_2.geometry} material={materials.mata1} position={[-1860.141, -1.792, 1376.813]} rotation={[-Math.PI, 0.497, -Math.PI]} />
          <mesh geometry={nodes.polySurface4_mata1_0_2.geometry} material={materials.mata1} position={[-264.852, 18.042, 326.801]} scale={0.648} />
          <mesh geometry={nodes.polySurface1_mata1_0_2.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface3_mata1_0_2.geometry} material={materials.mata1} />
          <mesh geometry={nodes.polySurface5_mata1_0_2.geometry} material={materials.mata1} position={[-1029.308, 16.007, 147.375]} rotation={[0, 1.025, 0]} scale={0.689} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
