/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: guenhag (https://sketchfab.com/guenhag)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-school-d3eec954bc51453e825e392a59b28b78
Title: High School
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function School(props) {
  const { nodes, materials } = useGLTF(import.meta.env.VITE_S3_URL + 'Map/School/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[25.353, 24.694, 12.411]} scale={[5.916, 11.751, 4.881]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.009']} />
      </group>
      <group position={[25.346, 27.399, 11.822]} scale={[0.901, 2.439, 0.301]}>
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.004']} />
      </group>
      <group position={[25.349, 23.769, 12.018]} scale={[0.981, 0.933, 0.261]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
      </group>
      <group position={[22.609, 23.769, 12.018]} scale={[1.048, 0.933, 0.261]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.001']} />
      </group>
      <group position={[28.078, 23.769, 12.018]} scale={[1.048, 0.933, 0.261]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
      </group>
      <group position={[25.357, 15.444, 7.749]} scale={[7.745, 7.746, 7.746]}>
        <mesh geometry={nodes.Object_42.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material.019']} />
      </group>
      <group position={[25.361, 9.803, 15.449]} scale={[1.381, 2.769, 0.161]}>
        <mesh geometry={nodes.Object_55.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
      </group>
      <group position={[20.81, 9.803, 15.449]} scale={[1.388, 2.769, 0.161]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_59.geometry} material={materials['Material.001']} />
      </group>
      <group position={[29.909, 9.803, 15.449]} scale={[1.388, 2.769, 0.161]}>
        <mesh geometry={nodes.Object_61.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
      </group>
      <group position={[25.343, 16.746, 14.198]} scale={[1.287, 2.034, 0.261]}>
        <mesh geometry={nodes.Object_72.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_73.geometry} material={materials['Material.001']} />
      </group>
      <group position={[107.024, 9.07, 50.207]} rotation={[0, -1.073, 0]} scale={[5.03, 2.229, 0.129]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Material} />
      </group>
      <group position={[77.508, 2.827, 15.961]} rotation={[0, 0.013, 0]}>
        <mesh geometry={nodes.Object_89.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_91.geometry} material={materials['Material.001']} />
      </group>
      <group position={[32.372, 13.144, 16.194]} rotation={[0, -Math.PI / 2, 0]} scale={[2.114, 2.162, 1.826]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials.light_mat_1002} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.light_mat_1001} />
      </group>
      <group position={[27.663, 13.144, 16.194]} rotation={[0, -Math.PI / 2, 0]} scale={[2.114, 2.162, 1.826]}>
        <mesh geometry={nodes.Object_104.geometry} material={materials.light_mat_1002} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.light_mat_1001} />
      </group>
      <group position={[23.046, 13.144, 16.194]} rotation={[0, -Math.PI / 2, 0]} scale={[2.114, 2.162, 1.826]}>
        <mesh geometry={nodes.Object_107.geometry} material={materials.light_mat_1002} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.light_mat_1001} />
      </group>
      <group position={[18.316, 13.144, 16.194]} rotation={[0, -Math.PI / 2, 0]} scale={[2.114, 2.162, 1.826]}>
        <mesh geometry={nodes.Object_110.geometry} material={materials.light_mat_1002} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.light_mat_1001} />
      </group>
      <group position={[26.034, 15.203, 15.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_113.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_114.geometry} material={materials['Material.016']} />
      </group>
      <group position={[24.682, 15.203, 15.49]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_116.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_117.geometry} material={materials['Material.016']} />
      </group>
      <group position={[25.234, 0, 88.327]}>
        <mesh geometry={nodes.Object_155.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_156.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_157.geometry} material={materials['Material.014']} />
      </group>
      <group position={[30.596, 15.203, 15.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_159.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_160.geometry} material={materials['Material.016']} />
      </group>
      <group position={[29.243, 15.203, 15.49]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_162.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_163.geometry} material={materials['Material.016']} />
      </group>
      <group position={[21.497, 15.203, 15.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_167.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_168.geometry} material={materials['Material.016']} />
      </group>
      <group position={[20.145, 15.203, 15.49]} scale={[0.519, 0.445, 1.84]}>
        <mesh geometry={nodes.Object_170.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_171.geometry} material={materials['Material.016']} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} position={[25.346, 30.108, 12.178]} scale={[0.078, 0.139, 0.109]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Material} position={[25.348, 27.385, 11.872]} scale={[0.021, 1.652, 0.019]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.008']} position={[25.351, 31.909, 12.071]} scale={[0.05, 0.674, 0.075]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material.002']} position={[25.356, 0.481, 30.568]} scale={[11.435, 0.261, 0.387]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Material} position={[22.75, 27.385, 11.872]} scale={[0.022, 1.652, 0.019]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Material} position={[28.052, 27.385, 11.872]} scale={[0.025, 1.652, 0.019]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} position={[30.513, 33.014, 12.728]} scale={[1.037, 0.043, 0.078]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.008']} position={[20.22, 32.646, 12.711]} scale={0.261} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Material.008']} position={[30.532, 32.646, 12.711]} scale={0.261} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material_0} position={[20.201, 33.014, 12.728]} scale={[1.037, 0.043, 0.078]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.002']} position={[68.777, 19.011, 8.222]} scale={[0.455, 0.311, 0.39]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['Material.002']} position={[25.347, 2.479, 21.893]} scale={[12.138, 5.167, 6.935]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials['Material.008']} position={[29.911, 20.475, 15.529]} scale={[1.411, 0.09, 0.092]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials['Material.008']} position={[25.369, 19.285, 15.572]} scale={[0.066, 0.118, 0.092]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials['Material.008']} position={[25.363, 20.475, 15.529]} scale={[1.375, 0.09, 0.092]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials['Material.008']} position={[20.809, 20.475, 15.529]} scale={[1.394, 0.09, 0.092]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Material.008']} position={[32.508, 27.868, 14.628]} scale={[0.261, 0.261, 0.059]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['Material.008']} position={[40.548, 27.868, 14.628]} scale={[0.261, 0.261, 0.059]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Material.008']} position={[10.153, 27.868, 14.628]} scale={[0.261, 0.261, 0.059]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.008']} position={[18.193, 27.868, 14.628]} scale={[0.261, 0.261, 0.059]} />
      <mesh geometry={nodes.Object_75.geometry} material={materials['Material.001']} position={[77.952, 15.326, 10.776]} rotation={[Math.PI / 2, 0, -0.988]} scale={[2.792, 0.261, 8.465]} />
      <mesh geometry={nodes.Object_77.geometry} material={materials['Alum-BlueGray']} position={[29.884, 20.874, 15.525]} rotation={[0, 0, -Math.PI / 2]} scale={[4.378, 5.779, 10.966]} />
      <mesh geometry={nodes.Object_79.geometry} material={materials['Material.008']} position={[36.516, 27.823, 14.588]} scale={[0.143, 0.143, 0.076]} />
      <mesh geometry={nodes.Object_81.geometry} material={materials['Material.008']} position={[14.161, 27.823, 14.588]} scale={[0.143, 0.143, 0.076]} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Material} position={[65.646, 15.293, 11.579]} scale={[5.03, 2.229, 0.129]} />
      <mesh geometry={nodes.Object_93.geometry} material={materials['Alum-BlueGray']} position={[25.33, 20.874, 15.525]} rotation={[0, 0, -Math.PI / 2]} scale={[4.378, 5.779, 10.966]} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['Alum-BlueGray']} position={[20.787, 20.874, 15.525]} rotation={[0, 0, -Math.PI / 2]} scale={[4.378, 5.779, 10.966]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials['Alum-BlueGray']} position={[14.108, 28.338, 14.58]} rotation={[0, 0, -Math.PI / 2]} scale={[1.096, 14.836, 10.966]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials['Alum-BlueGray']} position={[36.465, 28.338, 14.58]} rotation={[0, 0, -Math.PI / 2]} scale={[1.096, 14.836, 10.966]} />
      <mesh geometry={nodes.Object_119.geometry} material={materials['Material.020']} position={[32.372, 13.301, 16.526]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.material_0} position={[32.372, 13.042, 15.996]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.material_0} position={[32.372, 13.042, 16.027]} scale={[0.726, 0.892, 1.125]} />
      <mesh geometry={nodes.Object_125.geometry} material={materials['Material.020']} position={[27.664, 13.301, 16.526]} />
      <mesh geometry={nodes.Object_127.geometry} material={materials.material_0} position={[27.664, 13.042, 15.996]} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.material_0} position={[27.664, 13.042, 16.027]} scale={[0.726, 0.892, 1.125]} />
      <mesh geometry={nodes.Object_131.geometry} material={materials['Material.020']} position={[23.046, 13.301, 16.526]} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.material_0} position={[23.046, 13.042, 15.996]} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.material_0} position={[23.046, 13.042, 16.027]} scale={[0.726, 0.892, 1.125]} />
      <mesh geometry={nodes.Object_137.geometry} material={materials['Material.020']} position={[18.316, 13.301, 16.526]} />
      <mesh geometry={nodes.Object_139.geometry} material={materials.material_0} position={[18.316, 13.042, 15.996]} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.material_0} position={[18.316, 13.042, 16.027]} scale={[0.726, 0.892, 1.125]} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.material_0} position={[32.373, 12.656, 16.521]} scale={0.418} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.material_0} position={[31.195, 13.375, 16.186]} rotation={[Math.PI / 2, 0, 0]} scale={[0.021, 0.401, 0.021]} />
      <mesh geometry={nodes.Object_147.geometry} material={materials.material_0} position={[27.665, 12.656, 16.521]} scale={0.418} />
      <mesh geometry={nodes.Object_149.geometry} material={materials['Material.015']} position={[25.355, 17.474, 15.427]} rotation={[Math.PI / 2, 0, 0]} scale={[0.519, 1.84, 0.445]} />
      <mesh geometry={nodes.Object_151.geometry} material={materials.material_0} position={[23.048, 12.656, 16.521]} scale={0.418} />
      <mesh geometry={nodes.Object_153.geometry} material={materials.material_0} position={[18.318, 12.656, 16.521]} scale={0.418} />
      <mesh geometry={nodes.Object_165.geometry} material={materials['Material.015']} position={[29.917, 17.474, 15.427]} rotation={[Math.PI / 2, 0, 0]} scale={[0.519, 1.84, 0.445]} />
      <mesh geometry={nodes.Object_173.geometry} material={materials['Material.015']} position={[20.818, 17.474, 15.427]} rotation={[Math.PI / 2, 0, 0]} scale={[0.519, 1.84, 0.445]} />
      <mesh geometry={nodes.Object_175.geometry} material={materials.Clear_Glass} position={[25.35, 17.858, 15.534]} scale={[1.793, 1, 1]} />
      <mesh geometry={nodes.Object_177.geometry} material={materials.Clear_Glass} position={[29.912, 17.858, 15.534]} scale={[1.793, 1, 1]} />
      <mesh geometry={nodes.Object_179.geometry} material={materials.Clear_Glass} position={[20.814, 17.858, 15.534]} scale={[1.793, 1, 1]} />
    </group>
  )
}