/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Shayan4321 (https://sketchfab.com/Shayan4321)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basket-ball-court-65b160fdee7d42f8b0a7e99e0fc8ec5b
Title: BASKET BALL COURT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BasketBall_court(props) {
  const { nodes, materials } = useGLTF('https://b305finalproject.s3.ap-northeast-2.amazonaws.com/Map/BasketBall_Court/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-32.247, 471.878, 43.427]} rotation={[-Math.PI / 2, 0, 0]} scale={258.845}>
          <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube_Material012_0.geometry} material={materials['Material.012']} />
        </group>
        <group position={[835.314, 1021.517, 43.427]} rotation={[3.142, -1.568, 3.142]} scale={[208.806, 110.773, 141.634]}>
          <mesh geometry={nodes.Plane001_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane001_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Plane001_Material004_0.geometry} material={materials.material_0} />
        </group>
        <group position={[977.607, 511.866, 43.427]} rotation={[-Math.PI / 2, 0, 0]} scale={[24.765, 31.635, 27.534]}>
          <mesh geometry={nodes.Cube002_Material004_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Cube002_Material012_0.geometry} material={materials['Material.012']} />
        </group>
        <group position={[660.797, 520.83, 676.811]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]}>
          <mesh geometry={nodes.Cylinder007_Material004_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Cylinder007_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-517.834, 520.83, 676.811]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]}>
          <mesh geometry={nodes.Cylinder001_Material004_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-517.834, 520.83, -698.373]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]}>
          <mesh geometry={nodes.Cylinder003_Material004_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Cylinder003_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[482.297, 1129.859, 860.534]} rotation={[-Math.PI / 2, 0, -0.014]} scale={[4.266, 24.519, 18.726]}>
          <mesh geometry={nodes.Cube003_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube003_Material015_0.geometry} material={materials['Material.015']} />
        </group>
        <group position={[-669.868, 1129.859, 860.534]} rotation={[-Math.PI / 2, 0, -0.014]} scale={[4.266, 24.519, 18.726]}>
          <mesh geometry={nodes.Cube004_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube004_Material015_0.geometry} material={materials['Material.015']} />
        </group>
        <group position={[-669.692, 1129.859, -759.823]} rotation={[-Math.PI / 2, 0, -3.135]} scale={[4.266, 24.519, 18.726]}>
          <mesh geometry={nodes.Cube006_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube006_Material015_0.geometry} material={materials['Material.015']} />
        </group>
        <group position={[498.495, 1129.859, -759.823]} rotation={[-Math.PI / 2, 0, -3.135]} scale={[4.266, 24.519, 18.726]}>
          <mesh geometry={nodes.Cube007_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube007_Material015_0.geometry} material={materials['Material.015']} />
        </group>
        <group position={[-883.325, 1021.517, 43.475]} rotation={[0, 1.57, 0]} scale={[208.806, 110.773, 141.634]}>
          <mesh geometry={nodes.Plane003_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane003_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Plane003_Material004_0.geometry} material={materials.material_0} />
        </group>
        <group position={[-1025.617, 511.866, 43.985]} rotation={[-Math.PI / 2, 0, -3.138]} scale={[24.765, 31.635, 27.534]}>
          <mesh geometry={nodes.Cube009_Material004_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Cube009_Material012_0.geometry} material={materials['Material.012']} />
        </group>
        <mesh geometry={nodes.Plane_Material003_0.geometry} material={materials['Material.003']} position={[-32.247, 492.743, 43.427]} rotation={[-Math.PI / 2, 0, 0]} scale={222.559} />
        <mesh geometry={nodes.Cube001_Material005_0.geometry} material={materials['Material.005']} position={[822.724, 950.6, 43.463]} rotation={[-Math.PI / 2, 0, 0]} scale={20.091} />
        <mesh geometry={nodes.Circle_Material005_0.geometry} material={materials['Material.005']} position={[766.574, 951.488, 43.463]} rotation={[-Math.PI / 2, 0, 0]} scale={34.565} />
        <mesh geometry={nodes.Cylinder__0.geometry} material={materials.Cylinder__0} position={[766.574, 914.923, 43.463]} rotation={[-Math.PI / 2, 0, 0]} scale={33.754} />
        <mesh geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} position={[509.548, 590.745, -630.259]} rotation={[-Math.PI / 2, 0, 0]} scale={180.184} />
        <mesh geometry={nodes.Cylinder009_Material004_0.geometry} material={materials.material_0} position={[660.797, 520.83, -597.665]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]} />
        <mesh geometry={nodes.Cylinder010_Material004_0.geometry} material={materials.material_0} position={[364.109, 520.83, -597.665]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]} />
        <mesh geometry={nodes.Cylinder011_Material004_0.geometry} material={materials.material_0} position={[660.797, 520.83, -664.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]} />
        <mesh geometry={nodes.Cylinder012_Material004_0.geometry} material={materials.material_0} position={[364.109, 520.83, -664.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.383, 5.383, 71.106]} />
        <mesh geometry={nodes.Cube008_Material005_0.geometry} material={materials['Material.005']} position={[-870.735, 950.6, 43.395]} rotation={[-Math.PI / 2, 0, -3.138]} scale={20.091} />
        <mesh geometry={nodes.Circle001_Material005_0.geometry} material={materials['Material.005']} position={[-814.586, 951.488, 43.194]} rotation={[-Math.PI / 2, 0, -3.138]} scale={34.565} />
        <mesh geometry={nodes.Cylinder002__0.geometry} material={materials.Cylinder__0} position={[-814.586, 914.923, 43.194]} rotation={[-Math.PI / 2, 0, -3.138]} scale={33.754} />
        <mesh geometry={nodes.Cube010_Material005_0.geometry} material={materials['Material.005']} position={[-1058.163, 661.364, 990.71]} rotation={[-Math.PI / 2, 0, 0]} scale={[222.559, 6.053, 157.956]} />
        <mesh geometry={nodes.Cube011_Material005_0.geometry} material={materials['Material.005']} position={[434.068, 661.364, 990.71]} rotation={[-Math.PI / 2, 0, 0]} scale={[222.559, 6.053, 157.956]} />
        <mesh geometry={nodes.Cube012_Material005_0.geometry} material={materials['Material.005']} position={[-1021.817, 690.445, -898.917]} rotation={[-Math.PI / 2, 0, 0]} scale={[222.559, 6.053, 157.956]} />
        <mesh geometry={nodes.Cube013_Material005_0.geometry} material={materials['Material.005']} position={[-1296.592, 690.445, 738.528]} rotation={[-Math.PI / 2, 0, 1.572]} scale={[214.472, 6.053, 157.956]} />
        <mesh geometry={nodes.Cube014_Material005_0.geometry} material={materials['Material.005']} position={[1230.816, 690.445, 738.528]} rotation={[-Math.PI / 2, 0, 1.566]} scale={[214.472, 6.053, 157.956]} />
      </group>
    </group>
  )
}