/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: adynhaidar (https://sketchfab.com/adynhaidar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/studio-office-interior-6e41320708f74a6ba974ff8c26746ed8
Title: Studio Office Interior
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {

  const { nodes, materials } = useGLTF('https://b305finalproject.s3.ap-northeast-2.amazonaws.com/Map/House/scene.gltf')

  useEffect(() => {
    if (props.onLoaded) {
      props.onLoaded();
    }
  }, [props, props.onLoaded]);

  return (
    <group {...props} dispose={null}>
      <group scale={0.0015}>
        <group position={[2172.522, 993.558, 2689.763]} rotation={[-Math.PI / 2, 0, 1.715]} scale={184.358}>
          <mesh geometry={nodes.Drink_Tray_Drink_Tray_0.geometry} material={materials.Drink_Tray} />
          <mesh geometry={nodes.Drink_Pot_Drink_Tray_0.geometry} material={materials.Drink_Tray} />
          <mesh geometry={nodes.Little_Glass_A_Drink_Tray_0.geometry} material={materials.Drink_Tray} position={[0.359, -0.459, 0.067]} />
          <mesh geometry={nodes.Little_Glass_B_Drink_Tray_0.geometry} material={materials.Drink_Tray} position={[-0.195, -0.711, 0.067]} />
        </group>
        <group position={[2533.614, 890.921, 3393.525]} rotation={[-Math.PI / 2, 0, -1.961]} scale={31.541}>
          <mesh geometry={nodes.Laptop_Keyboard_Laptop_0.geometry} material={materials.Laptop} />
          <mesh geometry={nodes.Laptop_Lid_Laptop_0.geometry} material={materials.Laptop} position={[-2.642, 0, -0.024]} rotation={[Math.PI, -1.36, Math.PI]} />
        </group>
        <group position={[-907.169, 1545.456, -489.099]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Wall_B_Wall_B_0.geometry} material={materials.Wall_B} />
          <mesh geometry={nodes.Mounted_Flower_Pot_Mounted_Flower_Pot_0.geometry} material={materials.Mounted_Flower_Pot} position={[-1.808, 0, -2.177]} rotation={[0, 0, -Math.PI]} scale={1.7} />
        </group>
        <group position={[-849.283, 777.688, 4053.772]} rotation={[-Math.PI / 2, 0, -1.072]} scale={100}>
          <mesh geometry={nodes.Briefing_Lamp_Briefing_Lamp_0.geometry} material={materials.Briefing_Lamp} />
          <mesh geometry={nodes.Briefing_Lamp_Headlamp_Briefing_Lamp_0.geometry} material={materials.Briefing_Lamp} position={[0.025, 2.365, 5.802]} rotation={[0.579, 0, 0]} />
        </group>
        <group position={[1578.874, 303.783, 234.233]} rotation={[-Math.PI / 2, 0, 2.212]} scale={52.476}>
          <mesh geometry={nodes.Mini_Table_Mini_Table_0.geometry} material={materials.Mini_Table} />
          <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} position={[-1.217, 0, 2.511]} scale={1.429} />
          <mesh geometry={nodes.Bread_Bread_0.geometry} material={materials.Bread} position={[1.917, -0.055, 2.295]} rotation={[0, 0, -0.608]} scale={3.113} />
        </group>
        <group position={[4234.229, 497.306, 788.148]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={191.632}>
          <mesh geometry={nodes.Dispenser_Table_Dispenser_Table_0.geometry} material={materials.Dispenser_Table} />
          <mesh geometry={nodes.Water_Dispenser_Water_Dispenser_0.geometry} material={materials.Water_Dispenser} position={[0, 0, 3.357]} />
          <mesh geometry={nodes.Water_Gallon_Water_Gallon_0.geometry} material={materials.Water_Gallon} position={[0, 0, 3.357]} />
        </group>
        <group position={[2535.053, 630.631, 663.718]} rotation={[-Math.PI / 2, 0, -0.385]} scale={410.951}>
          <mesh geometry={nodes.Bananas_Bowl_of_Bananas_0.geometry} material={materials.Bowl_of_Bananas} />
          <mesh geometry={nodes.Bananas_A_Bowl_of_Bananas_0.geometry} material={materials.Bowl_of_Bananas} position={[-0.15, -0.364, -0.004]} />
          <mesh geometry={nodes.Bananas_B_Bowl_of_Bananas_0.geometry} material={materials.Bowl_of_Bananas} position={[-0.133, -0.21, 0.005]} rotation={[0.261, 0.146, -0.535]} />
          <mesh geometry={nodes.Bananas_C_Bowl_of_Bananas_0.geometry} material={materials.Bowl_of_Bananas} position={[-0.136, -0.287, 0.119]} rotation={[-1.774, 1.359, -0.1]} />
          <mesh geometry={nodes.Bananas_D_Bowl_of_Bananas_0.geometry} material={materials.Bowl_of_Bananas} position={[-0.053, -0.392, 0.072]} rotation={[1.073, 1.055, 0.171]} />
        </group>
        <mesh geometry={nodes['8_Scattered_Papers_B_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[-845.925, 159.977, 4158.858]} rotation={[-Math.PI / 2, 0, 2.725]} scale={92.147} />
        <mesh geometry={nodes['8_Scattered_Papers_C_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[402.06, 803.984, 3862.992]} rotation={[-Math.PI / 2, 0, 1.156]} scale={104.753} />
        <mesh geometry={nodes['8_Scattered_Papers_E_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[3162.823, 878.341, 3462.709]} rotation={[-Math.PI / 2, 0, -0.17]} scale={77.037} />
        <mesh geometry={nodes['8_Scattered_Papers_I_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[1570.106, 1180.448, -1934.576]} rotation={[-Math.PI / 2, 0, -0.382]} scale={108.595} />
        <mesh geometry={nodes['8_Scattered_Papers_A_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[-2945.251, 935.338, 2695.596]} rotation={[-Math.PI / 2, 0, 2.059]} scale={76.025} />
        <mesh geometry={nodes['8_Scattered_Papers_G_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[2853.257, 589.101, 614.638]} rotation={[-Math.PI / 2, 0, 0.275]} scale={87.607} />
        <mesh geometry={nodes['8_Scattered_Papers_F_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[3566.155, 152.972, 1678.584]} rotation={[-Math.PI / 2, 0, 0.587]} scale={81.154} />
        <mesh geometry={nodes['8_Scattered_Papers_H_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[1014.312, 162.372, 190.224]} rotation={[-1.568, -0.06, 0.57]} scale={108.353} />
        <mesh geometry={nodes['8_Scattered_Papers_D_8_Scattered_Papers_0'].geometry} material={materials['8_Scattered_Papers']} position={[746.239, 664.81, 3550.75]} rotation={[-1.585, 0.044, 0.459]} scale={86.945} />
        <mesh geometry={nodes['3_Paper_Balls_A_3_Paper_Balls_0'].geometry} material={materials['3_Paper_Balls']} position={[1880.046, 1643.492, -2012.837]} rotation={[2.063, 0.471, 1.259]} scale={108.353} />
        <mesh geometry={nodes['3_Paper_Balls_B_3_Paper_Balls_0'].geometry} material={materials['3_Paper_Balls']} position={[2707.417, 219.514, 390.146]} rotation={[-Math.PI / 2, 0, 0]} scale={108.353} />
        <mesh geometry={nodes['3_Paper_Balls_C_3_Paper_Balls_0'].geometry} material={materials['3_Paper_Balls']} position={[156.576, 215.948, 1565.31]} rotation={[-1.043, 0.04, 1.557]} scale={105.274} />
        <mesh geometry={nodes['5_Poster_A_5_Poster_0'].geometry} material={materials['5_Poster']} position={[-3335.52, 1144.317, 4368.965]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={90.622} />
        <mesh geometry={nodes['5_Poster_C_5_Poster_0'].geometry} material={materials['5_Poster']} position={[-2445.866, 2119.072, 797.198]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={130.118} />
        <mesh geometry={nodes['5_Poster_F_5_Poster_0'].geometry} material={materials['5_Poster']} position={[-2120.713, 2044.066, 676.752]} rotation={[-Math.PI / 2, 0, 0]} scale={188.399} />
        <mesh geometry={nodes['5_Poster_D_5_Poster_0'].geometry} material={materials['5_Poster']} position={[1401.617, 2142.075, -2270.325]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={125.745} />
        <mesh geometry={nodes.Book_T_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1960.711, 494.706, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_O_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1226.418, 874.734, -1996.682]} rotation={[3.141, 0.111, 1.58]} scale={88.165} />
        <mesh geometry={nodes.Book_P_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1132.083, 893.051, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_S_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[2020.28, 494.706, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_Z_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1079.674, 493.619, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_A_A_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1013.551, 492.188, -1996.682]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_J_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1997.567, 897.104, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_A_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1985.146, 1295.028, -1996.682]} rotation={[-Math.PI / 2, -0.157, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_B_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1911.264, 1293.396, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_K_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1944.319, 895.917, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_M_A_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1726.371, 805.952, -1996.682]} rotation={[0, 0.914, 0]} scale={88.165} />
        <mesh geometry={nodes.Book_R_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1008.554, 894.144, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_N_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1219.854, 893.421, -2134.576]} rotation={[-1.608, 0, -3.121]} scale={88.165} />
        <mesh geometry={nodes.Book_Q_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1069.749, 895.824, -1996.682]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_G_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1247.696, 1293.569, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_I_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1029.906, 1292.6, -1996.682]} rotation={[-Math.PI / 2, -0.23, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_F_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1305.408, 1292.442, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_L_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1696.583, 859.423, -1996.682]} rotation={[Math.PI, 0.811, -Math.PI]} scale={88.165} />
        <mesh geometry={nodes.Book_H_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1172.029, 1297.531, -1996.682]} rotation={[-Math.PI / 2, 0.183, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_E_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1366.632, 1293.155, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_C_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1847.885, 1292.358, -1996.682]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_D_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1787.83, 1291.979, -1996.682]} rotation={[-Math.PI / 2, 0.039, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_Y_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1157.739, 494.818, -1996.682]} rotation={[-Math.PI / 2, -0.14, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_X_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1240.689, 493.619, -1996.682]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_W_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1304.038, 488.473, -1996.682]} rotation={[-Math.PI / 2, -0.066, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_U_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1889.104, 494.064, -1996.682]} rotation={[-Math.PI / 2, 0.161, Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Book_M_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1300.549, 887.29, -1958.111]} rotation={[0, -0.22, 1.676]} scale={88.165} />
        <mesh geometry={nodes.Book_V_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1363.219, 475.851, -2024.892]} rotation={[Math.PI, 0, 1.442]} scale={88.165} />
        <mesh geometry={nodes.Aesthetic_Floor_Aesthetic_Floor_remastered_0.geometry} material={materials.Aesthetic_Floor_remastered} position={[0, -27.772, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Study_Lamp_Study_Lamp001_0.geometry} material={materials['Study_Lamp.001']} position={[-3199.898, 920.863, 2489.912]} rotation={[-Math.PI / 2, 0, 0.319]} scale={5.139} />
        <mesh geometry={nodes.Study_Lamp_Head_Study_Lamp001_0.geometry} material={materials['Study_Lamp.001']} position={[-3199.898, 920.863, 2489.912]} rotation={[-Math.PI / 2, 0, 0.319]} scale={5.139} />
        <mesh geometry={nodes.Wool_Duster_Wool_Duster_0.geometry} material={materials.Wool_Duster} position={[-845.054, 2029.734, -2266.487]} rotation={[-1.683, 0, Math.PI]} scale={147.92} />
        <mesh geometry={nodes.Plant_Vase_Plant_Vase_0.geometry} material={materials.Plant_Vase} position={[665.647, 811.305, -2105.91]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={252.162} />
        <mesh geometry={nodes.Bulk_Pot_Bulk_Pot_0.geometry} material={materials.Bulk_Pot} position={[3683.08, 154.554, 3340.841]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[136.184, 106.333, 104.003]} />
        <mesh geometry={nodes.Bedside_Lamp_B_Bedside_Lamp_B_0.geometry} material={materials.Bedside_Lamp_B} position={[1083.063, 1747, -2029.797]} rotation={[-Math.PI / 2, 0, 0]} scale={[147.104, 114.859, 112.343]} />
        <mesh geometry={nodes.Desk_Books_Desk_Books_0.geometry} material={materials.Desk_Books} position={[-3047.279, 318.915, -592.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={237.393} />
        <mesh geometry={nodes.Mounted_TV_and_Remote_Mounted_TV_0.geometry} material={materials.Mounted_TV} position={[-3268.692, 1994.537, -640.609]} rotation={[-Math.PI / 2, 0.09, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Empty_Pot_Empty_Pot_0.geometry} material={materials.Empty_Pot} position={[4179.927, 262.513, 738.687]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[183.438, 143.228, 140.091]} />
        <mesh geometry={nodes.Pot_Pot_0.geometry} material={materials.material} position={[-1070.955, 269.322, 1051.668]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={116.614} />
        <mesh geometry={nodes.Exterior_Door_Living_Room_Door_0.geometry} material={materials.Living_Room_Door} position={[4020.331, 971.33, -2242.923]} rotation={[-Math.PI / 2, 0, -1.216]} scale={184.358} />
        <mesh geometry={nodes.Refrigator_Refrigator_0.geometry} material={materials.Refrigator} position={[2610.359, 484.662, -1956.711]} rotation={[-Math.PI / 2, 0, 0]} scale={338.388} />
        <mesh geometry={nodes.Bag_of_tools_Bag_of_tools_0.geometry} material={materials.Bag_of_tools} position={[-2912.079, 353.367, 3461.115]} rotation={[-Math.PI / 2, 0, 0.087]} scale={273.142} />
        <mesh geometry={nodes.Drawer_Base_Drawer_0.geometry} material={materials.Drawer} position={[-2925.704, 517.672, 4323.604]} rotation={[1.571, 0, Math.PI]} scale={207.866} />
        <mesh geometry={nodes.Alarm_Clock_Alarm_Clock_0.geometry} material={materials.Alarm_Clock} position={[-3199.733, 1065.645, 2707.91]} rotation={[-Math.PI / 2, 0, 2.546]} scale={207.866} />
        <mesh geometry={nodes.Small_Desk_Calendar_Small_Desk_Calendar_0.geometry} material={materials.Small_Desk_Calendar} position={[-1617.71, 977.409, 963.278]} rotation={[-Math.PI / 2, 0, -0.933]} scale={165.377} />
        <mesh geometry={nodes.Bedside_Lamp_A_Bedside_Lamp_A_0.geometry} material={materials.Bedside_Lamp_A} position={[-3108.009, 867.156, 4410.443]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={158.351} />
        <mesh geometry={nodes.Pensil_Cup_A_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[3371.52, 974.573, 2813.024]} rotation={[-Math.PI / 2, 0, -2.733]} scale={207.866} />
        <mesh geometry={nodes.Paper_Script_Paper_Script_0.geometry} material={materials.Paper_Script} position={[-2896.589, 934.617, 3080.815]} rotation={[-Math.PI / 2, 0, -1.287]} scale={100} />
        <mesh geometry={nodes.Championship_Charter_Champion_Cup_0.geometry} material={materials.Champion_Cup} position={[-3180.917, 1161.612, 3571.106]} rotation={[-Math.PI / 2, 0, -1.067]} scale={162.832} />
        <mesh geometry={nodes.Eraser_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[3202.033, 888.781, 2775.237]} rotation={[-Math.PI / 2, 0, -0.22]} scale={207.866} />
        <mesh geometry={nodes.Vase_Pot_Vase_Pot_0.geometry} material={materials.Vase_Pot} position={[2101.139, 876.247, 3229.351]} rotation={[-Math.PI / 2, 0, 0.809]} scale={264.401} />
        <mesh geometry={nodes.Window_Curtain_Window_Curtain_0.geometry} material={materials.Window_Curtain} position={[410.832, 1590.406, -2218.788]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Office_Mat_Office_Mat_0.geometry} material={materials.Office_Mat} position={[-668.618, 161.448, -1797.6]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Window_and_Glass_Window_and_Glass_0.geometry} material={materials.Window_and_Glass} position={[-396.268, 1521.93, -2353.328]} rotation={[-Math.PI / 2, 0, -1.421]} scale={100} />
        <mesh geometry={nodes.Film_Poster_Film_Poster_0.geometry} material={materials.Film_Poster} position={[-3275.06, 1844.466, 4077.63]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={90.792} />
        <mesh geometry={nodes.Foreground_Foreground_0.geometry} material={materials.Foreground} position={[0, -131.656, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Shortfilm_Poster_Shortfilm_Poster_0.geometry} material={materials.Shortfilm_Poster} position={[-1451.051, 1967.182, 811.961]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={92.841} />
        <mesh geometry={nodes.Window_Layer_Window_and_Glass_0.geometry} material={materials.Window_and_Glass} position={[-907.169, 1545.456, -489.099]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Rounded_Table_Rounded_Table_0.geometry} material={materials.Rounded_Table} position={[2614.278, 499.936, 722.907]} rotation={[-Math.PI / 2, 0, 0]} scale={608.032} />
        <mesh geometry={nodes.Guest_Chair_Guest_Chair_0.geometry} material={materials.Guest_Chair} position={[2598.799, 572.637, -405.519]} rotation={[-Math.PI / 2, 0, -0.674]} scale={85.451} />
        <mesh geometry={nodes.Office_Telephone_Office_Telephone_0.geometry} material={materials.Office_Telephone} position={[2098.945, 888.027, 3557.153]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={110.811} />
        <mesh geometry={nodes.Book_Shelf_and_Books_Book_Shelf_and_Books_0.geometry} material={materials.Book_Shelf_and_Books} position={[1469.207, 12.441, -1976.067]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={88.165} />
        <mesh geometry={nodes.Employee_Chair_A_Employee_Chair_0.geometry} material={materials.Employee_Chair} position={[35.816, 549.415, 0]} rotation={[-Math.PI / 2, 0, -2.23]} scale={146.854} />
        <mesh geometry={nodes.Briefing_Chair_A_Briefing_Chair_C_0.geometry} material={materials.Briefing_Chair_C} position={[694.109, 631.744, 3426.653]} rotation={[-Math.PI / 2, 0, -0.513]} scale={100} />
        <mesh geometry={nodes.LCD_Monitor_A_LCD_Monitor_B_0.geometry} material={materials.LCD_Monitor_B} position={[-2173.227, 1214.214, 1102.547]} rotation={[-Math.PI / 2, 0, 0]} scale={120.892} />
        <mesh geometry={nodes.Black_Bag_Black_Bag_0.geometry} material={materials.Black_Bag} position={[-569.232, 345.919, 558.742]} rotation={[-Math.PI / 2, 0, 0]} scale={121.247} />
        <mesh geometry={nodes.Manager_Table_Manager_Table_0.geometry} material={materials.Manager_Table} position={[2156.207, -416.781, 2970.056]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Large_Book_A_Large_Book_0.geometry} material={materials.Large_Book} position={[2932.677, 897.117, 3257.72]} rotation={[-Math.PI / 2, 0, -1.06]} scale={100} />
        <mesh geometry={nodes.Brainstorming_Table_Brainstorming_Table_0.geometry} material={materials.Brainstorming_Table} position={[-185.287, 777.688, 3465.356]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Manager_Chair_A_Manager_Chair_0.geometry} material={materials.Manager_Chair} position={[3039.896, 370.308, 3690.325]} rotation={[-Math.PI / 2, 0, -1.846]} scale={77.408} />
        <mesh geometry={nodes.Storyboard_Sheet_Storyboard_Sheet_0.geometry} material={materials.Storyboard_Sheet} position={[-302.568, 805.421, 3272.961]} rotation={[-Math.PI / 2, 0, 1.28]} scale={110.971} />
        <mesh geometry={nodes.Table_Barrier_Table_Barrier_0.geometry} material={materials.Table_Barrier} position={[2703.888, 1042.383, 3038.85]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Briefing_Lamp_Hinge_Briefing_Lamp_0.geometry} material={materials.Briefing_Lamp} position={[-849.283, 777.688, 4053.772]} rotation={[-Math.PI / 2, 0, -1.595]} scale={100} />
        <mesh geometry={nodes.Employee_Table_A_Employee_Table_0.geometry} material={materials.Employee_Table} position={[-501.782, 652.499, -146.757]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={130.998} />
        <mesh geometry={nodes.Employee_Table_B_Employee_Table_B_0.geometry} material={materials.Employee_Table_B} position={[-2026.47, 652.499, 1204.831]} rotation={[-Math.PI / 2, 0, 0]} scale={130.998} />
        <mesh geometry={nodes.Medium_Table_Medium_Table_0.geometry} material={materials.Medium_Table} position={[667.879, 150.547, -2023.407]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Trash_Can_Trash_Can_0.geometry} material={materials.Trash_Can} position={[-380.324, 429.944, -968.736]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={126.941} />
        <mesh geometry={nodes.Shoes_B_Shoes_0.geometry} material={materials.Shoes} position={[3121.065, 214.939, -53.722]} rotation={[0, 0.318, 0]} scale={100} />
        <mesh geometry={nodes.Mounted_Table_Mounted_Table_0.geometry} material={materials.Mounted_Table} position={[-3381.716, -416.781, 2919.178]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Manager_Chair_B_Manager_Chair_0.geometry} material={materials.Manager_Chair} position={[2383.391, 370.308, 3662.078]} rotation={[-Math.PI / 2, 0, -1.46]} scale={77.408} />
        <mesh geometry={nodes.Manager_Chair_C_Manager_Chair_B_0.geometry} material={materials.Manager_Chair_B} position={[2387.054, 370.308, 1982.383]} rotation={[-Math.PI / 2, 0, 2.072]} scale={77.408} />
        <mesh geometry={nodes.Manager_Chair_D_Manager_Chair_0.geometry} material={materials.Manager_Chair} position={[3071.589, 370.308, 2448.982]} rotation={[-Math.PI / 2, 0, 1.294]} scale={77.408} />
        <mesh geometry={nodes.Employee_Chair_B_Employee_Chair_B_0.geometry} material={materials.Employee_Chair_B} position={[-2210.656, 546.31, 1713.253]} rotation={[-Math.PI / 2, 0, 2.7]} scale={146.854} />
        <mesh geometry={nodes.TV_Remote_TV_Remote_0.geometry} material={materials.TV_Remote} position={[-3047.791, 914.912, -313.976]} rotation={[-Math.PI / 2, 0, -1.416]} scale={100} />
        <mesh geometry={nodes.Soft_Carpet_Soft_Carpet_0.geometry} material={materials.Soft_Carpet} position={[-1935.919, 163.096, -592.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Box_A_Box_B_0.geometry} material={materials.Box_B} position={[-3096.466, 285.961, 3605.317]} rotation={[-Math.PI / 2, 0, -1.693]} scale={273.142} />
        <mesh geometry={nodes.Box_B_Box_A_0.geometry} material={materials.Box_A} position={[-2770.818, 311.732, 3731.879]} rotation={[-Math.PI / 2, 0, -0.904]} scale={273.142} />
        <mesh geometry={nodes.Plastic_Glass_Plastic_Glass_0.geometry} material={materials.Plastic_Glass} position={[2745.204, 673.648, 948.888]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[183.438, 143.228, 140.091]} />
        <mesh geometry={nodes.LCD_Monitor_B_LCD_Monitor_0.geometry} material={materials.LCD_Monitor} position={[-588.262, 1214.214, -1.641]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={120.892} />
        <mesh geometry={nodes.Briefing_Chair_B_Briefing_Chair__0.geometry} material={materials.Briefing_Chair} position={[-145.934, 627.217, 2758.049]} rotation={[-Math.PI / 2, 0, 0.22]} scale={125.881} />
        <mesh geometry={nodes.Briefing_Chair_C_Briefing_Chair_B_0.geometry} material={materials.Briefing_Chair_B} position={[-1354.429, 627.217, 3583.905]} rotation={[-Math.PI / 2, 0, 1.337]} scale={125.881} />
        <mesh geometry={nodes.Artist_Chair_Artist_Chair_0.geometry} material={materials.Artist_Chair} position={[-2299.177, 652.479, 2884.163]} rotation={[-Math.PI / 2, 0, -1.089]} scale={146.854} />
        <mesh geometry={nodes.Large_Book_B_Large_Book_0.geometry} material={materials.Large_Book} position={[2932.677, 868.144, 3257.72]} rotation={[-Math.PI / 2, 0, -0.766]} scale={100} />
        <mesh geometry={nodes.Drawer_Puller_B_Drawer_0.geometry} material={materials.Drawer} position={[-2780.649, 436.288, 4320.83]} rotation={[1.571, 0, Math.PI]} scale={207.866} />
        <mesh geometry={nodes.Coffe_Cup_A_Cup_of_Coffee_0.geometry} material={materials.Cup_of_Coffee} position={[2668.944, 585.971, 722.259]} rotation={[-Math.PI / 2, 0, 0.468]} scale={410.951} />
        <mesh geometry={nodes.Pensil_Single_A_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[3293.242, 882.374, 2680.897]} rotation={[-Math.PI / 2, 0, 0.185]} scale={207.866} />
        <mesh geometry={nodes.Lemons_A_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2637.257, 1940.297, -1762.179]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Bowl_of_Lemons_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2604.567, 1930.752, -1818.841]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Lemons_C_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2677.198, 1933.711, -1836.21]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Lemons_E_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2622.134, 1937.235, -1899.491]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Lemons_D_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2543.979, 1935.102, -1874.752]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Lemons_F_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2586.168, 1994.568, -1830.706]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.Lemons_B_Bowl_of_Lemons_0.geometry} material={materials.Bowl_of_Lemons} position={[2548.567, 1925.003, -1792.318]} rotation={[-Math.PI / 2, 0, 0]} scale={303.453} />
        <mesh geometry={nodes.TV_Desk_TV_Desk_0.geometry} material={materials.TV_Desk} position={[-3047.279, 318.915, -592.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={237.393} />
        <mesh geometry={nodes.DVD_DVD_0.geometry} material={materials.material_76} position={[-3047.279, 318.915, -592.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={237.393} />
        <mesh geometry={nodes.TV_Speaker_TV_Speaker_0.geometry} material={materials.TV_Speaker} position={[-3047.279, 318.915, -592.873]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={237.393} />
        <mesh geometry={nodes.Round_Carpet_Round_Carpet_0.geometry} material={materials.Round_Carpet} position={[2115.476, 160.141, 157.311]} rotation={[-Math.PI / 2, 0, -1.252]} scale={100} />
        <mesh geometry={nodes.Coffe_Cup_B_Cup_of_Coffee_0.geometry} material={materials.Cup_of_Coffee} position={[2536.135, 585.971, 503.237]} rotation={[-Math.PI / 2, 0, -0.446]} scale={410.951} />
        <mesh geometry={nodes.After_The_Storm_Poster_Beach_Play_Poster_0.geometry} material={materials.Beach_Play_Poster} position={[-906.105, 1753.52, 235.733]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Refrigator_Notes_D_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2486.147, 1577.853, -1498.797]} rotation={[-1.628, 0, 0]} scale={[202.509, 290.178, 290.178]} />
        <mesh geometry={nodes.Refrigator_Photo_A_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2807.843, 1299.118, -1499.041]} rotation={[-Math.PI / 2, 0, 0]} scale={338.388} />
        <mesh geometry={nodes.Refrigator_Notes_A_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2446.722, 1730.411, -1498.797]} rotation={[-1.628, 0, 0]} scale={100} />
        <mesh geometry={nodes.Refrigator_Notes_E_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2799.036, 1527.406, -1499.107]} rotation={[-1.65, 0, 0]} scale={338.388} />
        <mesh geometry={nodes.Refrigator_Notes_F_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2645.83, 1348.158, -1499.591]} rotation={[-1.619, 0, 0]} scale={243.051} />
        <mesh geometry={nodes.Refrigator_Notes_B_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2558.543, 1722.357, -1498.797]} rotation={[-1.628, 0, 0]} scale={100} />
        <mesh geometry={nodes.Refrigator_Photo_B_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2639.032, 871.109, -1497.656]} rotation={[-1.596, 0, 0]} scale={338.388} />
        <mesh geometry={nodes.Refrigator_Notes_C_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2673.262, 1721.135, -1498.797]} rotation={[-1.628, 0, 0]} scale={100} />
        <mesh geometry={nodes.Pensil_Cup_B_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[-3147.998, 1029.54, 3323.137]} rotation={[-Math.PI / 2, 0, -2.733]} scale={207.866} />
        <mesh geometry={nodes.Eraser_B_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[-3010.686, 941.204, 3463.394]} rotation={[-Math.PI / 2, 0, -0.701]} scale={207.866} />
        <mesh geometry={nodes.Pensil_Single_B_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[-3037.229, 934.796, 3353.291]} rotation={[-Math.PI / 2, 0, -1.344]} scale={207.866} />
        <mesh geometry={nodes.Plane_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[3417.778, 877.519, 2605.636]} rotation={[-Math.PI / 2, 0, 0.063]} scale={100} />
        <mesh geometry={nodes.Plane001_Underworld_Poster_0.geometry} material={materials.Underworld_Poster} position={[-1721.311, 1772.732, -2230.239]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane003_Office_Stationary_0.geometry} material={materials.Office_Stationary} position={[-3010.682, 877.519, 2758.846]} rotation={[-Math.PI / 2, 0, -2.07]} scale={100} />
        <mesh geometry={nodes.Paper_Bundle_Paper_Bundle_0.geometry} material={materials.Paper_Bundle} position={[-134.127, 917.77, 3860.79]} rotation={[-Math.PI / 2, 0, 0.254]} scale={100} />
        <mesh geometry={nodes.Drawer_Puller_A_Drawer_0.geometry} material={materials.Drawer} position={[-2587.762, 670.937, 4320.836]} rotation={[1.571, 0, Math.PI]} scale={207.866} />
        <mesh geometry={nodes.Briefing_Carpet_Briefing_Carpet_0.geometry} material={materials.Briefing_Carpet} position={[-183.068, 145.982, 3298.203]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Refrigator_Notes_G_Colored_Notes_0.geometry} material={materials.Colored_Notes} position={[2436.458, 1035.385, -1499.591]} rotation={[-1.601, -0.006, 0]} scale={243.051} />
        <mesh geometry={nodes.Girl_Potrait_Girl_Potrait_0.geometry} material={materials.Girl_Potrait} position={[-3288.963, 1838.215, 1747.222]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={108.006} />
        <mesh geometry={nodes.Door_Layer_Living_Room_Door_0.geometry} material={materials.Living_Room_Door} position={[3318.481, 1138.613, -2235.597]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={184.358} />
        <mesh geometry={nodes.Keyboard_A_Keyboard_0.geometry} material={materials.Keyboard} position={[-2266.732, 1214.214, 1102.546]} rotation={[-Math.PI / 2, 0, 0]} scale={120.892} />
        <mesh geometry={nodes.Keyboard_B_Keyboard_0.geometry} material={materials.Keyboard} position={[-603.168, 1214.214, 93.151]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={120.892} />
        <mesh geometry={nodes.Mousepads_A_Mousepads_A_0.geometry} material={materials.Mousepads_A} position={[-394.512, 980.308, -421.464]} rotation={[-Math.PI / 2, 0, -0.123]} scale={100} />
        <mesh geometry={nodes.Mousepads_B_Mousepads_B_0.geometry} material={materials.Mousepads_B} position={[-1738.612, 980.308, 1288.699]} rotation={[-Math.PI / 2, 0, -1.741]} scale={100} />
        <mesh geometry={nodes.Mouse_A_Mouse_0.geometry} material={materials.Mouse} position={[-1752.117, 997.681, 1311.202]} rotation={[-Math.PI / 2, 0, 0]} scale={120.892} />
        <mesh geometry={nodes.Mouse_B_Mouse_0.geometry} material={materials.Mouse} position={[-394.512, 997.681, -421.464]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={120.892} />
        <mesh geometry={nodes.Broom_Broom_0.geometry} material={materials.Broom} position={[-3305.595, 1123.101, 1161.402]} rotation={[-Math.PI / 2, 0.019, -Math.PI / 2]} scale={102.556} />
        <mesh geometry={nodes['5_Poster_B_5_Poster_0'].geometry} material={materials['5_Poster']} position={[-3333.687, 1268.695, 2031.743]} rotation={[0, 0, -Math.PI / 2]} scale={120.682} />
        <mesh geometry={nodes.Opened_Book_Opened_Book_0.geometry} material={materials.Opened_Book} position={[2831.5, 894.918, 2619.344]} rotation={[-Math.PI / 2, 0, 0.278]} scale={235.372} />
        <mesh geometry={nodes.Planning_Board_Planning_Board_0.geometry} material={materials.Planning_Board} position={[-3293.993, 1586.95, 2973.481]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Wall_A_Wall_A_0.geometry} material={materials.Wall_A} position={[-907.169, 1545.456, -489.099]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Pillow_Pillow_0.geometry} material={materials.Pillow} position={[-1659.397, 240.056, -655.773]} rotation={[-1.604, 0.139, 0.233]} scale={100} />
        <mesh geometry={nodes.Wall_Clock_Wall_Clock_0.geometry} material={materials.Wall_Clock} position={[-911.597, 2147.66, -309.665]} rotation={[2.644, Math.PI / 2, 0]} scale={206.541} />
        <mesh geometry={nodes.Box_C_Box_C_0.geometry} material={materials.Box_C} position={[1625.341, 1683.959, -1988.951]} rotation={[-Math.PI / 2, 0, 0.291]} scale={85.187} />
        <mesh geometry={nodes.Blank_Border_Wall_A_0.geometry} material={materials.Wall_A} position={[12.808, 1493.29, -2552.427]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Toy_Car_Red_Toy_Car_Red_0.geometry} material={materials.Toy_Car_Red} position={[3323.755, 876.448, 3233.326]} rotation={[-Math.PI / 2, 0, 0.628]} scale={237.393} />
        <mesh geometry={nodes.Toy_Car_Blue_Toy_Car_Blue_0.geometry} material={materials.Toy_Car_Blue} position={[1313.386, 1600.869, -2016.428]} rotation={[-Math.PI / 2, 0, -0.785]} scale={237.393} />
        <mesh geometry={nodes.Window_and_Glass001_Volumetric_Lights_0.geometry} material={materials.Volumetric_Lights} position={[-396.268, 1521.93, -2353.328]} rotation={[-Math.PI / 2, 0, -1.421]} scale={100} />
        <mesh geometry={nodes.Window_and_Glass002_Volumetric_Lights_0.geometry} material={materials.Volumetric_Lights} position={[3710.225, 2333.771, -2258.469]} rotation={[-Math.PI / 2, 0, -1.421]} scale={100} />
        <mesh geometry={nodes.Window_and_Glass003_Volumetric_Lights_0.geometry} material={materials.Volumetric_Lights} position={[2555.468, 2333.771, -2258.469]} rotation={[-Math.PI / 2, 0, -1.421]} scale={100} />
        <mesh geometry={nodes.Sky_Volumetric_Lights_0.geometry} material={materials.Volumetric_Lights} position={[12.808, 1493.29, -2552.427]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
      </group>
    </group>
  )
}
